### ISSUE TITLE
Rescue Raiders crashes on //c+

### ISSUE THREAD

**Issue by frankmilliron** [a2-4am/4cade#103]
Just after the copyright info past the first intro screen. Crashes to monitor. Let me know what I can do to diagnose.

**Comment by frankmilliron** [comment]
Tried this on actual hardware with some breakpoints installed (wasn't able to recreate in MAME). Crashes at 63C8:JSR $D800 because ROM is switched in instead of Bank 1 of LC.

**Comment by frankmilliron** [comment]
Don't see it using WAIT/FCA8 anywhere.  ?

**Comment by frankmilliron** [comment]
Confirmed "+READ_RAM1_WRITE_RAM1" just before the prelaunch JMP $404A fixes Rescue Raiders with //c+. Doesn't affect any other machines I tested.

**Comment by frankmilliron** [comment]
I was wrong about C060 and annunciators. They had no effect. But I will admit I don't know where it's being switched back to ROM.

**Comment by peterferrie** [comment]
It's the disk access code which is checking which bank was active at
the time in order to know how to switch back to it on exit, since the
I/O code is in banked LC.
On the IIc+, we must be seeing a colliding value that's confusing the
switching code.

**Comment by frankmilliron** [comment]
fixed
