### ISSUE TITLE
Dino Eggs hung in level 9

### ISSUE THREAD

**Issue by wyatt-wong** [a2-4am/4cade#110]
I found Dino Eggs hung in level 9 using TotalReplay 3.0
<img width="1106" alt="Screen Shot 2020-01-26 at 9 20 15 PM" src="https://user-images.githubusercontent.com/10095648/73135810-a0be3400-4081-11ea-9b19-0dfdd74ee9df.png">

**Comment by peterferrie** [comment]
The image is missing a level.  I'll fix it.

**Comment by wyatt-wong** [comment]
> The image is missing a level. I'll fix it.

How come this issue happened In TotalReplay 3.0 while Dino Eggs was fine in TotalReplay 2.0

**Comment by peterferrie** [comment]
> How come this issue happened In TotalReplay 3.0 while Dino Eggs was fine in
> TotalReplay 2.0

It's not okay.  2.0 hangs in the same way and for the same reason.

**Comment by wyatt-wong** [comment]
> How come this issue happened In TotalReplay 3.0 while Dino Eggs was fine in TotalReplay 2.0
> It's not okay. 2.0 hangs in the same way and for the same reason.

No not really. I could play Dino Eggs Level 9

**Comment by wyatt-wong** [comment]
Any update yet?

**Comment by peterferrie** [comment]
Yes.
Fixed in d1f4e7b7f8e61c60137494c2b3b0887783977209
