### ISSUE TITLE
The lives in Mr. Do will NOT be decreased in TotalReplay 3.0

### ISSUE THREAD

**Issue by wyatt-wong** [a2-4am/4cade#111]
I found that the lives in Mr. Do will NOT be decreased in TotalReplay 3.0 even after I lost a life.
<img width="1113" alt="Screen Shot 2020-01-27 at 12 52 30 AM" src="https://user-images.githubusercontent.com/10095648/73138599-711e2480-409f-11ea-9d6c-0c8e13a02203.png">

**Comment by peterferrie** [comment]
Cheat mode got enabled permanently by accident.  I'll fix it.

**Comment by wyatt-wong** [comment]
> Cheat mode got enabled permanently by accident. I'll fix it.

Again the Mr. Do in TotalReplay 2.0 is fine.

**Comment by peterferrie** [comment]
Yes, I know.  It happened when switching the 48kb and 128kb versions
to use a single loader.  It's fixed in the repo now.

**Comment by wyatt-wong** [comment]
> Yes, I know. It happened when switching the 48kb and 128kb versions to use a single loader. It's fixed in the repo now.

So I need to rebuild TotalReplay by myself if I want to get the latest fix ASAP ?

**Comment by peterferrie** [comment]
Yes.

**Comment by wyatt-wong** [comment]
> Yes.

I will wait for fix in Dino Eggs Level 9 as well.
