### ISSUE TITLE
Build error in macOS

### ISSUE THREAD

**Issue by wyatt-wong** [a2-4am/4cade#112]
I got build error in macOS.

<img width="682" alt="Screen Shot 2020-01-27 at 11 37 19 AM" src="https://user-images.githubusercontent.com/10095648/73148897-8627a180-40f9-11ea-81bc-7f49eef50eec.png">

**Comment by wyatt-wong** [comment]
I found that the build works only if I used "git clone https://github.com/a2-4am/4cade.git" command to clone the repository to my Mac. If I simply download this repository as a ZIP file, the build will fail.

**Comment by frankmilliron** [comment]
There's an invisible folder '.git' which stores the build number.

**Comment by wyatt-wong** [comment]
> There's an invisible folder '.git' which stores the build number.

My point is the Makefile should NOT rely on the build number in the hidden folder .git. For those who download the 4cade-master.zip from Github, the build will failed due to missing the hidden .git folder.

**Comment by a2-4am** [comment]
We display the build number on startup, in order to be able to investigate bug reports from people running unofficial builds. This has proved very useful, even among the core developers. Calculating the build number relies on the git history. I will update the build documentation to make this clear, but we will not be changing the feature itself.

**Comment by wyatt-wong** [comment]
> We display the build number on startup, in order to be able to investigate bug reports from people running unofficial builds. This has proved very useful, even among the core developers. Calculating the build number relies on the git history. I will update the build documentation to make this clear, but we will not be changing the feature itself.

I do NOT object your choice to use build number. But I thought there should be an alternative to retrieve the build number other than using "git rev-list --count HEAD"
