### ISSUE TITLE
Press first letter did not go to the first game of the letter?

### ISSUE THREAD

**Issue by wyatt-wong** [a2-4am/4cade#114]
I remembered the TotalReplay claimed that press the first letter will go to the first game of the letter but it doesn't seem to be the case. 

For example, I press D and directly go to Drol instead of directly go to "David's Midnight Magic". Is that the normal behavior ?

**Comment by a2-4am** [comment]
It does not necessarily go to the first game of the letter. It goes to the best match, as determined by a text ranking algorithm that takes a number of factors into account, including whether a character is the first letter of a word, how close multiple characters are to each other, and the total length of the game name.
