### ISSUE TITLE
Some games do not appear on Floppy Emu equipped //c

### ISSUE THREAD

**Issue by NathanCzaja** [a2-4am/4cade#115]
I've noticed several games aren't present when using total reply with my Floppy Emu equipped apple //c. They cannot be found using Search or Browse mode. This issue has appeared in previous versions of Total Replay that I've used.

Missing titles:
- Airheart
- Arkanoid
- Axis Assassin
- Bad Dudes
- Ball Blazer
- Batman
- Battlezone
- BC's Quest for Tires
- Bruce Lee
- Bubble Bobble
- Ceiling Zero
- Choplifter
- Crisis Mountain
- David's Midnight Magic
- Defender
- Diamond Mine
- Dino Eggs
- Donkey Kong
- Drelbs
- Frogger-II
- Galaxian
- Galaxy Gates
- Gamma Goblins
- Heavy Barrel
- HERO
- Impossible Mission
- Kamikaze
- Laser Bounce
- Lost Tomb
- Mad Bomber
- Marble Madness
- Miner2049er
- Mr. Do!
- Mr. Robot
- Night Mission Pinball
- Phantoms Five
- Pitfall-II
- Phantom
- Qix
- Quadrant 6112
- Red Alert
- Renegade
- Shamus
- Skyfox
- Space Eggs
- Stargate
- The Goonies
- Tomahawk
- Tubeway ][
- Xevious
- Zaxxon

Version I'm using: 
Revision 3.0; Serial Number 20200121

System Info: 
ROM 4X apple //c
RamExpress II A2S4000
Floppy Emu Revision C

also occurred with the //c's original ROM 0 w/o ram expansion

**Comment by a2-4am** [comment]
Do you have a joystick? If so, does the loading screen (that gives the version number and the amount of memory found) say it found a joystick?

**Comment by NathanCzaja** [comment]
I currently have a mouse plugged in. Loading screen does not say it found a joystick.

I'm guessing that certain titles are only available when a joystick is detected?

**Comment by a2-4am** [comment]
Correct. If no joystick is detected, Total Replay filters out any game that requires a joystick. (Similarly, if you run it on a machine with only 64K,it will filter out any game that requires 128K.)
