### ISSUE TITLE
A.E. Small slip

### ISSUE THREAD

**Issue by MarcoVerpelli** [a2-4am/4cade#144]
Hello ProDOS dynamic duo!

Either change pathname in LOADER.SYS or rename A.E in A.E.

Marco

**Comment by peterferrie** [comment]
We discard LOADER.SYSTEM when we build for TR, which is why I didn't
notice this (I had to rename A.E. to A.E because the trailing '.' was
being lost during build).
The Asimov version works.

**Comment by MarcoVerpelli** [comment]
OK, got it, I close, thanks

Marco
