### ISSUE TITLE
Games and self-running demos fail to load on my //c using SmartPort SD adapter.

### ISSUE THREAD

**Issue by ArgGrr** [a2-4am/4cade#154]
As detailed, all games on V3 fail to load on my //c using this Arduino smart port to SD adapter:
http://www.users.on.net/~rjustice/SmartportCFA/SmartportSD.htm

When I select a game, the screen goes black, and there is constant drive activity. The game never seems to load. The same happens if I let the screen saver/attact mode run. It will cycle through screen shots, but when it comes to what I assume is a self-running demo, It hangs with disk activity on a black screen.

If I press CTRL-Reset the first time, disk activity stops, but it remains on a black screen. Pressing it a second time returns me to Total Replay.

On v1, some games do load, such as Moon Patrol, Batman to name a couple.

I am running v0 //c ROM. Will upgrade to 4x as soon as I can get my spare EPROM to erase.

I have not had any luck getting Pitch Dark and Pitch Darker to work, but haven't done anything other an a quick test so far.

I have another ProDOS image with Bitsy Bye (I think you know this :) on it, and a collection of games & utils. These launch fine, although I have the //c colour issue, no zip chip.

**Comment by frankmilliron** [comment]
We've had other reports of other esoteric smartport hardware failing to work with TR. Be interesting to know whether this setup works on the v3 or v4 //c EPROM versions. Wondering if zero page usage may be to blame as well? I do not have hardware to test.

**Comment by ArgGrr** [comment]
I have an eprom eraser inbound. I'll be able to test any of the //c roms when it gets here.

**Comment by frankmilliron** [comment]
Actually, now that I think of it, the v0 ROM doesn't allow for SmartPort (or maybe I'm thinking of the v255 -- the first version, second version is v0. PRINT PEEK (64447) will tell you). You may need to cut a trace for certain EPROMs to work correctly.
https://www.bigmessowires.com/2015/05/29/apple-iic-rom-upgrade/

**Comment by ArgGrr** [comment]
Yes you are thinking of the original v255. PEEK (64447) = 0 in my case.
V0 added the SmartPort features and doubled the ROM size. This //c had the mod already done to it when I bought it, and well the SmartPort seems to be working. I can boot off a ProDOS volume after the Arduino warms up. Using Bitsy Bye, I can access all 4 volumes in Slots 7 and 2.
I haven't gone over and double checked the jumpers, or pulled the ROM yet and checked it's contents though.

**Comment by frankmilliron** [comment]
The Floppy Emu is the same way on the //c+. On power up, you have to wait until it loads itself and then force a reboot. Does it see all 32mb of your other images normally? Does it work with a Floppy Emu?
The website seems to show it booting GSOS so I can only assume it would potentially work. I'm a little more in the rather-buy-it-working-than-fuss-around-with-arduinos camp, however.

**Comment by ArgGrr** [comment]
I believe it can see the rest of the other images, I haven't had any reason to doubt it. I have Bitsy Bye on Slot 5.1, and version 1, 2 and the latest v3 of Total Replay on the other drives. I just use the TAB key to select the drive and Enter to launch Total Replay. I don't have the eject button wired up at this stage, that could be used to cycle boot image.
I don't have access to a Floppy Emu, can't test anything there. They are like $100, and it costs maybe $20 to put one of these together. 

I suspect the issue lies in the SmartPort Implementation of what I am using. The serial port has been configured for debug output. I'm going to look into this a bit more, see if I can capture what is happening. However, I am not knowledgeable on ProDOS, SmartPort or any of this modern stuff.

**Comment by frankmilliron** [comment]
A second hardware setup for sanity checking would be nice. :)
I have a v0 and a v4 //c but not your arduino project. Thought the BOOTI was a great deal at $50 (requires slots though) but I like the idea of $20 devices. The Floppy Emu is more expensive but also supports lot more modes like woz 5.25" floppy, vintage mac 400k/800k/1.4m floppy, in addition to 32mb smartport on devices like your //c.

looks like a buffer overrun? something's getting whacked out in the block count. Suggests some kind of firmware bug in the Arduino code, with a glitch in proRWST2 as a much more distant second.

**Comment by ArgGrr** [comment]
Ha I think I fixed it. It was the Arduino code. Going to let demo mode run for a bit to make sure.
I had to add some (unsigned short) casts to stop bytes overflowing and giving strange block numbers:

                       // block num 1st byte
                       block_num = (LBN & 0x7f) | (((unsigned short)LBH << 3) & 0x80);
                       // block num second byte
                       block_num = block_num + (((LBL & 0x7f) | (((unsigned short)LBH << 4) & 0x80))*256);

**Comment by frankmilliron** [comment]
I would submit your code change to Rob Justice so he can update his website.

**Comment by ArgGrr** [comment]
Yup sent off an email to both of them yesterday! :)
