### ISSUE TITLE
Castle Smurfenstein & Dino Smurf lowercase

### ISSUE THREAD

**Issue by frankmilliron** [a2-4am/4cade#163]
The lowercase text looks garbled on ][+ (which doesn't have lowercase). Both games use lowercase.
I tried to hook a callback into the output routine but couldn't figure out where to stick it. Uses the ROM string print routine though (Castle Smurf, anyway).

**Comment by frankmilliron** [comment]
I just modified the disk image for Smurfenstein so if you have to change something in there, please pick up my version with the reset vectors already fixed.

**Comment by peterferrie** [comment]
fixed in d23fe8397446be00cb663cbbb91e9c2c740a3f49
