### ISSUE TITLE
HGR version of Columns

### ISSUE THREAD

**Issue by cybernesto** [a2-4am/4cade#174]
Columns is a great addition to Total replay. Unfortunately only the DHGR version is currently available. Would it be possible to include the HGR version as well? See https://macgui.com/downloads/?file_id=3513

**Comment by a2-4am** [comment]
Great find. qkumba, please make it a single launcher like Tetris and Thexder.

**Comment by frankmilliron** [comment]
Here's an unshrunk, unbinscii'd version....
f
[Columns.2plus.po.zip](https://github.com/a2-4am/4cade/files/4567907/Columns.2plus.po.zip)

**Comment by peterferrie** [comment]
done in 188c908aae23a6a3a310fec93d2d2e7382be1e58
