### ISSUE TITLE
"Help" screen should allow jumping to ToggleCheat and Credits

### ISSUE THREAD

**Issue by frankmilliron** [a2-4am/4cade#179]
The initial help screen (accessed by "?") does not allow immediately showing the About screen by hitting "Ctrl-A" or turning on the cheat mode "Ctrl-C" while the help info is displayed. This might be confusing for users who assume the help screen can respond to requests that it's showing are valid input responses. TR does not currently jump to About or back to search mode with a toggled cheat state.

**Comment by peterferrie** [comment]
done in 0731ca7ba8449be5d5d375fcb0f9b6fbbfdcfcd9
