### ISSUE TITLE
Add joystick calibration option

### ISSUE THREAD

**Issue by a2-4am** [a2-4am/4cade#188]
MECC Computer Inspector is the "best of breed" for joystick calibration visualization

**Comment by frankmilliron** [comment]
I just noticed that "Ski Crazed" also has a built in visual calibrator.

**Comment by peterferrie** [comment]
Perhaps run it like a demo (i.e. external program which returns to TR) but launched via hot-key?

**Comment by a2-4am** [comment]
Fixed in https://github.com/a2-4am/4cade/commit/2272f7778934fd59ce731b578d677a24e5620370
