### ISSUE TITLE
Add prelaunch patch to change Falcons keys

### ISSUE THREAD

**Issue by roughana** [a2-4am/4cade#191]
Falcons accepts ; for left, left arrow for stop and right arrow for right. This combination suits a ][+ keyboard but is unwieldy for later machines and emulators.
Add a prelaunch patch to change the keys to J for left, K for stop and L for right.

Note: Falcons also supports an Apple III keyboard layout with a different combination. So patch the right place.

**Comment by peterferrie** [comment]
done in 33e9369ebb2dbec71e6b8b1da3f9e77106d178ef
