### ISSUE TITLE
Pending speech interrupt and other minor Mockingboard related things

### ISSUE THREAD

**Issue by tomcw** [a2-4am/4cade#197]
The following clean-up code for the Mockingboard's SSI263 speech chip detection is missing a few lines...

```
         lda   #0
@mb_smc9
         sta   $c440
         lda   #$70   ; (set CTL=0)
@mb_smc10
         sta   $c443
```

Should be:
```
         lda   #$80   ; missing (set CTL=1)
@mb_smc8b
         sta   $c443  ; missing
         lda   #0
@mb_smc9
         sta   $c440
         lda   #$70   ; (set CTL=0)
@mb_smc10
         sta   $c443
```

Basically you are not setting the Speech chip's mode to DISABLE_IRQ (done by setting CTL=1, then CTL=0). so the speech chip will play a "pause" phoneme, then set IFR=$02 (as the SSI263 is still in interrupt mode). Since you have already cleared b1 in IER, then this won't trigger an interrupt on the 6502 (even when flag I=0).

Probably a minor thing, but worth getting right not just for poorly written legacy games, but also because this code is being re-used in modern games (eg. a2bejewld... I've already raised a bug about this with @jeremysrand).

btw, the following code during (speech detection) setup isn't needed, as the speech chip doesn't use the 6522's DDRB/A regs ($c402 & $c403).

```
@mb_smc1
         sta   $c403
@mb_smc2
         sta   $c402
```

But the Speech chip's clean-up code (in `@mb_irq`) to restore DDRB/A ($c402 & $c403) to $ff & $7 respectively is probably good practice.

In fact I wonder if @peterferrie's latest fix (4adc3e860e99174) now doesn't work in the Mockingboard case _without_ speech chip? (Since DDRB/A will both still be $00)

I'd move the restore DDRB/A code out of `@mb_irq` and just before that fix.

**Comment by frankmilliron** [comment]
I just realized the noise I'm hearing on mine might be the speech chip, and not the AY. I don't have a non-speech mockingboard to test.

**Comment by tomcw** [comment]
Is it easy to just (carefully) pop it out?

**Comment by frankmilliron** [comment]
I don't want to risk damaging it as it's a bit rare and the machine is all set up, but I do have a RM Phasor clone I could dig out. Would that be the same equivalent as the Mockingboard?

**Comment by a2-4am** [comment]
I don't know the answer, but I also have that Phasor clone and I don't care if I break it.

**Comment by frankmilliron** [comment]
There's never 'just one' pop out when testing either. :)
Virtual II doesn't emulate the speech chip, but it seems to work with the new code.

**Comment by tomcw** [comment]
Yes, RM Phasor should be equivalent to Mockingboard.

If you can make a build available (from the current top-of-tree) then I'll gladly step through the TR code for both combo's (w/ and w/out Speech chip).

**Comment by peterferrie** [comment]
Tom,

> If you can make a build available (from the current top-of-tree) then I'll
> gladly step through the TR code for both combo's (w/ and w/out Speech
> chip).

I'll add your changes first, and then we can share a build with you.
Otherwise it won't be a good use of your time.
Thanks.

**Comment by tomcw** [comment]
@peterferrie sent me an updated build, which I've now tested:

- Mockingboard + speech:
  - can see int handler now disabling speech chip's IRQ
  - can see both 6522's being re-init'ed & AY's reset
- Mockingboard w/out speech:
  - can see both 6522's being re-init'ed & AY's reset
- No Mockingboard

Closing as fixed.

**Comment by tomcw** [comment]
btw. I didn't test the Mockingboard Sound I case, ie. where there's only a 6522 at $Cn00 (and not at $Cn80). I suppose pedantically during the exit code you shouldn't be touching the $Cn80 regs. But since those writes to $Cn80 will just be ignored, then I don't see any harm in them.

**Comment by frankmilliron** [comment]
Starting 'Battle Cruiser' seems to reduce the volume of the noise I hear once it's on, but doesn't remove it (the latest commit doesn't turn it off either). It's pretty difficult to trigger this speech chip noise now, so seems good enough to just keep this closed. Battle Cruiser is also a little wonky otherwise (volume gets set too loud), but whatever. They both work and it's more stable.
