### ISSUE TITLE
B.C. Quest for tires crashes at the end of level 1

### ISSUE THREAD

**Issue by flynnfrog** [a2-4am/4cade#200]
With cheat enabled, at the end of level 1 (after the jump over lava), the game just freezes : a single speaker beep that sounds like the standard beep at boot can be heard.

Latest version of TR (300 Games), tested on Applewin 1.29.2.0, in Enhanced Apple //e

**Comment by frankmilliron** [comment]
I think I have seen this one as well, but I didn't follow up on it. My notes mention on ][+ it crashes to monitor with $557D shown (after second red "lake" animation, once balls start dropping from the air).

**Comment by peterferrie** [comment]
fixed in 3c9826737b5f3384284cf66af11b314f220658c3
