### ISSUE TITLE
Destroyed car left on screen in Dino Smurf

### ISSUE THREAD

**Issue by wyatt-wong** [a2-4am/4cade#201]
When a car was destroyed in Dino Smurf, a dead car object will left on screen.

![Screen Shot 2020-05-17 at 8 14 00 PM](https://user-images.githubusercontent.com/10095648/82145127-425cd180-987b-11ea-8e05-beb4a67c20d2.png)

**Comment by peterferrie** [comment]
Please check the original (non-ProDOS) disk to see if it does the same.

**Comment by wyatt-wong** [comment]
I already checked the original DSK have the same issue. In fact I played with the DSK file and found the issue happened. Then I accidentally found Dino Smurf was embedded in Total Replay 3.0

**Comment by peterferrie** [comment]
Okay, so the bug is in the original game, not in the TR port.
Closing as won't fix.
