### ISSUE TITLE
fix Starglider high scores

### ISSUE THREAD

**Issue by frankmilliron** [a2-4am/4cade#204]

**Comment by frankmilliron** [comment]
![Screen Shot 2020-05-18 at 6 59 48 AM](https://user-images.githubusercontent.com/34376619/82222850-b4aecf80-98d6-11ea-9004-a0fc38bbcbac.png)

**Comment by peterferrie** [comment]
fixed in 4fb775448efd3420d036b302da0489ca98601dd5
