### ISSUE TITLE
Tetris crashing during boot for //e and enhanced //e

### ISSUE THREAD

**Issue by tomcw** [a2-4am/4cade#216]
During boot, Tetris is crashing to the monitor (AppleWin / model=Enhanced //e) and crashes when model = //e (ie. crashes with any model supporting DHires title screen).

NB. When model=Apple II+ (Hires title screen) then it works.

This is a build I got from @peterferrie on Monday - in bottom right corner it says:

```
      E715
build 1679
```

**Comment by peterferrie** [comment]
fixed in bf9d236f75fcaf561526629906211e833f86011b
