### ISSUE TITLE
Tetris 128k title screen has corrupted data

### ISSUE THREAD

**Issue by frankmilliron** [a2-4am/4cade#220]
The game plays fine otherwise. Tested on //e and //gs. Both show the same glitch.
![Tetris 128k](https://user-images.githubusercontent.com/34376619/82733496-13a28900-9cc9-11ea-9450-f059826b2652.JPG)

**Comment by peterferrie** [comment]
fixed in e473a430d99a9e0cae3e3cb4683a6e6b7929e1be
