### ISSUE TITLE
Paperboy exits to monitor after title screen

### ISSUE THREAD

**Issue by tomcw** [a2-4am/4cade#239]
TR v4.0-alpha1, AppleWin 1.29.13.0, model = //e or Enhanced //e
(with or without a Mockingboard in slot-4)

repro:
- select & run Paperboy
- after the Mindscape logo and Paperboy title screen it'll just exit to the monitor

**Comment by peterferrie** [comment]
fixed in ccccf87839c38bfa5cdb2dfc2ba905ce5615c74c
