### ISSUE TITLE
Last Ninja - Fastchip acceleration not working

### ISSUE THREAD

**Issue by frankmilliron** [a2-4am/4cade#256]
The old version of the prelauncher had the wrong filename and therefore wasn't being loaded before running the game. I updated the reset, but noticed that Last Ninja doesn't boot on my Fastchip-enabled machine. If I disable the 2 accel and 2 LC bankswitch entries it works fine.

**Comment by peterferrie** [comment]
fixed in d1ef1a4e89e1b6a84511161b85973208ef6b00b6
