### ISSUE TITLE
Exterminator - visual artifacts during gameplay

### ISSUE THREAD

**Issue by frankmilliron** [a2-4am/4cade#258]
Exterminator exhibits visual artifacts during gameplay, but not during the demo. Appears to be an off-by-one? Only appears on the main players spaceship.
<img width="1269" alt="Screen Shot 2020-06-08 at 10 10 44 PM" src="https://user-images.githubusercontent.com/34376619/84108506-375a1480-a9d5-11ea-89af-66f3c5a149c1.png">

**Comment by peterferrie** [comment]
Don't press keys after selecting Paddles.  It's a game bug.
