### ISSUE TITLE
Spare Change animated demo hang/crash

### ISSUE THREAD

**Issue by darkcrayon** [a2-4am/4cade#259]
Virtual II and MicroM8, hangs during cartoon demo.

I let the demo run on my IIGS (ROM 3, TWGS, vidHD, CFFA3k) and it crashed to monitor during Spare Change.

Can be fairly quickly reached by running Virtual II at full speed and waiting a little.

**Comment by frankmilliron** [comment]
Does it on my //e as well.

**Comment by peterferrie** [comment]
fixed in caa25082dd87f5390539b85cdc44a1399e76300e
