### ISSUE TITLE
Drol freezes on the IIGS

### ISSUE THREAD

**Issue by HelixNRG** [a2-4am/4cade#275]
Drol freezes just after loading on my ROM3 IIGS (Total Replay v3 stable release had no issues). It freezes at the point the title treatment would have risen from the second platform (you can just see it peeking it out).

**Comment by peterferrie** [comment]
Confirmed.  I'll check why.

**Comment by peterferrie** [comment]
fixed in 575eb67cef8ff37346eaaf6a2e9830e9842722e3
