### ISSUE TITLE
The Games Winter Edition – after practising some events returning to main menu actually resets

### ISSUE THREAD

**Issue by HelixNRG** [a2-4am/4cade#276]
The Games Winter Edition resets (my ROM3 IIGS at least) when exiting out of practising events luge, ice skating, speed skating, ski jumping. But returning to main menu from Downhill, or Slalom, or Cross Country events didn’t reset my IIGS.

**Comment by peterferrie** [comment]
Likely related to #286

**Comment by peterferrie** [comment]
Unfortunate but intentional behaviour.  The game has no memory to reload the event selection after certain events, and reboots instead.
