### ISSUE TITLE
Test Mockingboard titles that autodetect for compatibility with FastChip

### ISSUE THREAD

**Issue by roughana** [a2-4am/4cade#280]
It is probable that any title that detects the presence of a Mockingboard will not be able to detect properly if an accelerator is being used, especially a FastChip //e.

Titles that auto-detect will need to have their detection routines patched to allow them to still detect the Mockingboard with the FastChip in use.

Titles to check:
Apple Cider Spider
Bouncing Kumungas (Ctrl-S to enable MB)
Bejewelled
Zaxxon
Thunder Bombs

Instead of patching the games' own detection routines, the solution maybe to patch the titles to use the Mockingboard in the slot detected by TR.

**Comment by peterferrie** [comment]
We'll need to check the auto-slot code to see the proper list.
None of Apple Cider Spider, Bouncing Kamungas, or Thunder Bombs
auto-detect the MB.  They all ask the user for the slot.

**Comment by peterferrie** [comment]
@roughana I've assigned the testing to you since you have the card and we don't.

**Comment by peterferrie** [comment]
done in 6149eac1e86852d2f6286ce718a9c1d4ee7ad06e
