### ISSUE TITLE
CFFA with enabled "Use GS CDA" option causes random hangs and glitching

### ISSUE THREAD

**Issue by a2-4am** [a2-4am/4cade#286]
IIgs, latest build

**Comment by roughana** [comment]
I was able to avoid the examples of glitches with dip-switch 7 enabled. I turned off disk ][ emulation and reduced the number of smartport devices to 1.

**Comment by roughana** [comment]
Thread on csa2 https://groups.google.com/forum/#!topic/comp.sys.apple2/yJqhQIZ9E-c
Antoine asked Rich Dreher for more information on the functionality that the switch invokes.
http://dreher.net/forum1/viewtopic.php?f=16&t=622

**Comment by peterferrie** [comment]
fixed in 33d00fc978e800c9ca3c5d20b44a27352d767620
