### ISSUE TITLE
Hangs when launched from GS/OS Finder on >4th smartport device

### ISSUE THREAD

**Issue by roughana** [a2-4am/4cade#3]
GSport emulator on Windows. Added image to my existing config (s7d5), booting from Ewen's GSport starter kit image. When launching Total Replay from Finder, the screen clears and appears to enter an infinite loop. There is a repeating error visible on GSport log screen "Unknown prodos_unit: 16"

I would expect that if there are not enough resources available to launch properly that an error should be displayed. e.g. Can't launch from GS/OS.

**Comment by peterferrie** [comment]
So it's connected as a fifth SmartPort device on a single interface?
i.e. it ends up being mapped to S1D1 or something?
If so then please try connecting as one of the first four devices
instead, to see if the problem is the mapping.

**Comment by roughana** [comment]
It worked from s7d2.
I'll update the ticket later.

    On Saturday, 27 July 2019, 4:50:01 am AEST, Peter Ferrie <notifications@github.com> wrote:  
 
 So it's connected as a fifth SmartPort device on a single interface?
i.e. it ends up being mapped to S1D1 or something?
If so then please try connecting as one of the first four devices
instead, to see if the problem is the mapping.

**Comment by peterferrie** [comment]
> 4th device is not supported in ProRWTS.  This is a known limitation.
To fix it would require revisiting all ProRWTS-based games, and for some there isn't enough free memory to fit the needed additional code.
