### ISSUE TITLE
Miner 2049er crashes to monitor on reset

### ISSUE THREAD

**Issue by xotmatrix** [a2-4am/4cade#305]
During the title or configuration screens, before game play starts, pressing reset crashes to monitor. After game play has started or after it has ended, pressing reset reboots.

Tested on:
Apple //e (enhanced) hardware with BOOTI;
AppleWin Apple //e (standard and enhanced);
AppleWin Apple II+ locks up instead of crashing.

**Comment by frankmilliron** [comment]
Hmm it's trashing the hook at $100. Then it gets set to reboot just before gameplay starts. I'll see what I can do to fix it.

**Comment by frankmilliron** [comment]
moving the hook up to BFF0 fixes it on the title. I don't know where it's picking up the reboot vectors from once gameplay starts, though. It could theoretically return to TR.

**Comment by a2-4am** [comment]
Fixed in https://github.com/a2-4am/4cade/pull/306
