### ISSUE TITLE
Passing MB config to Berzap not working

### ISSUE THREAD

**Issue by rharke** [a2-4am/4cade#308]
Automatically selecting the Mockingboard in Berzap is not working for me (tested in a local build 1874).

Support was added in https://github.com/a2-4am/4cade/commit/07ca70aab8881b6ed4fe7ff7e8b7f04355ade736 but it is not working consistently for me. It works differently under emulation than real hardware, but neither seems correct.

Real hardware (IIe Platinum, 128K, ReactiveMicro MB in slot 4):

- ✅ Detects MB on boot
- ❌ MB is not selected in config when launching Berzap
- ❌ Title music does not play

Emulation (Virtual ][ 9.2, 128K, virtual MB in slot 4):

- ✅ Detects MB on boot
- ✅ MB is selected in config when launching Berzap
- ❌ Title music does not play automatically. If you enter/leave the config screen without changing anything, it plays.

**Comment by peterferrie** [comment]
Does the RM MB look like a Sound I?  Berzap doesn't offer Sound I support so we don't select it.
If you select the MB manually on hardware, does the music play?  If so, using which option?
Meanwhile, I'll check the TR code.

**Comment by rharke** [comment]
Ah, yeah, it probably does look like a Sound I. Only one of the AY-3s is installed at the moment, because the other one is defective. So that must be why it's not being auto-selected.

That being said, if I select Mockingboard A manually, it _does_ play music. Perhaps it's missing half the voices though.

**Comment by peterferrie** [comment]
Yes, you'll be getting only mono instead of stereo music in that case.

**Comment by peterferrie** [comment]
Fixed in ea70f3fbbcd8e5d77989ee089cbff145cc8d66f5
