### ISSUE TITLE
Launcher hangs on keypresses -- IIgs

### ISSUE THREAD

**Issue by ewindisch** [a2-4am/4cade#309]
Keypresses that presumably trigger search are causing hangs on my physical IIgs.

If the first keypress is a ?, the help menu does appear correctly.

Ctrl-Reset gives me a blank screen after the freeze (rather than displaying the launcher graphics)

My system has 8MB of RAM (GGlabs), Uthernet in Slot1, and Microdrive. I wrote the 32MB image to the third partition of my Microdrive using ADTPRO 2.0.2 using the Uthernet adapter.

**Comment by a2-4am** [comment]
Which version or build number are you using? (It displays in the text screen during startup.)

**Comment by ewindisch** [comment]
version 4.0-alpha.2 (from Archive.org)

**Comment by ewindisch** [comment]
apologizes, I had a bad transfer! TY
