### ISSUE TITLE
Crash on startup with Mockingboard Sound/Speech I

### ISSUE THREAD

**Issue by robjustice** [a2-4am/4cade#310]
TR crashes during the Mockingboard detection with a Sound/Speech I installed. This is using a non enhanced IIe with cffa3k, RamworksIII and the Sound/Speech I installed.

It displays Mockingboard in slot 4, then crashes, seems like the speech detection does not like the SC-01.

128K
Mockingboard in slot 4
03FD-    A=82 X=00 Y=84 P=36 S=c7

Using build 1878

Registers stay the same after the crash every time, but S seems to vary.

**Comment by robjustice** [comment]
![Sound-Speech-I](https://user-images.githubusercontent.com/18372125/88502829-1005e800-d013-11ea-8f55-0b8313da8355.JPG)
I did a quick reverse engineer of the schematic for the speech part. Then I noticed that one VIA is connected to IRQ, the other to NMI. See attached. So the detect routine looks like its triggering an NMI when a Sound Speech I is in. Its not a common card around, so a very edge case..

**Comment by peterferrie** [comment]
Thanks.  That explains the weird break address.  We have no handler at
that location.  I will add one.

**Comment by peterferrie** [comment]
might be fixed by 262e94540ccee347de24e925a7d056a724074092

**Comment by robjustice** [comment]
Let me test that out later and I'll let you know how it goes.

**Comment by robjustice** [comment]
That fixed the crash, so its seems an NMI is being triggered. We don't speech detected as this is not setting the flag, so we won't auto setup setup Crimewave. I'm a bit puzzled why though, as I double checked the board and nothing is hooked to CA1. Perhaps its floating and picking up some noise. Let me have a bit more of a play to confirm that the code that turns on the interrupt is actually allowing the NMI to happen.

**Comment by peterferrie** [comment]
I set the NMI handler to ignore the interrupt, assuming that the
channel that's hooked up would still trigger.  If that's not happening
then do I have things backwards and I should be writing to the other
channel instead?

**Comment by digarok** [comment]
I have a similar crash with:
Apple IIe Platinum
MockingBoard-T (slot-4)
CFFA3k (slot-7)

![image](https://user-images.githubusercontent.com/173105/88611834-87f20380-d04f-11ea-84e7-8edcf7b5d90a.png)

Total Replay v4.0-alpha2

**Comment by robjustice** [comment]
Thanks for sharing that. I had a look on the A2heaven website and can just see that this card has the nmi line connected. These mockingboards are a mess :-). I think this board is more of the older Sound II clone, but i cannot find any pics for one of those.

**Comment by robjustice** [comment]
I did some more investigation on this, sorry, turned into a longer story than I thought.
On the S/S I it has the CA1 inputs on both 6522's floating, ie no connection. These are input only pins, so no internal pullups. On the later A or C, they have 4.7k pullups to +5v on each CA1 input, and they are also wired to the SSI-263 socket. I did a test with the original version TR with no NMI handler, and added a 4.7k pullup on the S/S I cards CA1 input. Then the crash does not occur, so it confirms its the floating inputs causing the issue.

The other thing also is that the SC-01 speech chip is on the other 6522. But, its wired quite differently, so looking for an interrupt from CA1 is not going to work with it. Its not memory mapped like the SSI-263, but connected via portb on the 6522 and cb1 & cb2 lines. I think the best option is to leave the dummy NMI handler in, so that the MB clones and the S/S I with the NMI connected will not crash. And then add a further step to the detection routing to detect the SC-01.

I had a look on the S/S I demo disk and used some code from there as an example and added it in, see attached. This seems to work ok with S/S I, A or C MB. For some reason with the SC-01, its a bit noisy after the detect, not sure why, but i think its ok. Will read a bit more for that. I tweaked the wait timed loop, as when i added a second one and it was taking quite a while to check for the speech chips. I think there is still a good margin there with what i have used. This now gives the possibility of identifying the S/S I separately to the C if needed.

[hw.mockingboard.a.txt](https://github.com/a2-4am/4cade/files/5005439/hw.mockingboard.a.txt)

**Comment by robjustice** [comment]
Ok, seems this version does not leave things in a good state for the games. Will need some more work & testing.

**Comment by robjustice** [comment]
This is better, I realised that the code to set the ay's in a quiet state was affecting the SC01. Need to only do one for S/S I card. I rearranged things, but you'll need to wave you optimsing wand over it and give it a double check. Its getting long now..
[hw.mockingboard.a.txt](https://github.com/a2-4am/4cade/files/5006826/hw.mockingboard.a.txt)

**Comment by peterferrie** [comment]
Crime Wave sets the slot correctly now if it finds the MB.

**Comment by peterferrie** [comment]
This runs in the initialisation phase.  I can accept it as-is.  Merged, thanks.

**Comment by Lord-Nightmare** [comment]
robjustice: that Mockingboard Sound/Speech I, is the TP3 (pin 5) pin on the SC-01-A connected to anything other than Capacitor C11 to ground? do you have pictures of the board (since the Sound/Speech I went through a few minor hardware revisions)?
