### ISSUE TITLE
Microwave graphical glitches

### ISSUE THREAD

**Issue by a2-4am** [a2-4am/4cade#313]
IIgs

**Comment by frankmilliron** [comment]
Hmm not seeing this one on my ROM3

**Comment by peterferrie** [comment]
I couldn't reproduce it either but I suspect screen-hole damage.

**Comment by frankmilliron** [comment]
wonder if different ROM versions use those locations differently for acceleration. What version does LadyAiluros have?

**Comment by peterferrie** [comment]
She has a ROM1.

**Comment by peterferrie** [comment]
Likely related to #286

**Comment by roughana** [comment]
I was unable to reproduce on ROM 3

**Comment by peterferrie** [comment]
fixed in 33d00fc978e800c9ca3c5d20b44a27352d767620
