### ISSUE TITLE
Moon Patrol reset crashes to monitor

### ISSUE THREAD

**Issue by a2-4am** [a2-4am/4cade#314]
IIgs, after playing game

**Comment by frankmilliron** [comment]
Seems to work on Virtual II and an actual ][+, but not on an actual //e or //gs. (?)

**Comment by peterferrie** [comment]
It looks like stack corruption but I couldn't reproduce it yet.
The simplest thing might be to move the reset vector to somewhere else entirely.

**Comment by frankmilliron** [comment]
I tried $BFF0 last night which also didn't work. I didn't check whether it was being overwritten by anything though. Super weird because ROM is switched in, and the vectors are correct.

**Comment by peterferrie** [comment]
BFFx is part of the moon-base graphics.
Something in the $2xx range might be safer.

**Comment by frankmilliron** [comment]
Right. It's overwriting BFF0 directly after the JMP 919 unpack, but before the JMP 2728. Let me try $280.

**Comment by peterferrie** [comment]
fixed in 7b52e1e58457147f73997e807a4216bbed0c98bc.
Thanks to Frank M.
