### ISSUE TITLE
Joystick test shows button 1 & button 2 - inconsistent with game help

### ISSUE THREAD

**Issue by roughana** [a2-4am/4cade#320]
TR game help refers to button 0 and button 1.
The joystick test is using naming inconsistent with Apple II convention.
To avoid confusion, the joystick test should be showing button 0 and button 1.

**Comment by roughana** [comment]
MECC routine loads at $800
https://github.com/a2-4am/4cade/blob/master/res/JOYSTICK

**Comment by roughana** [comment]
It looks like the HGR content is loaded from the code and moved to the appropriate place on the HGR screen. Therefore some repainting of the HGR content will be necessary to change 1->0 and 2->1.

**Comment by roughana** [comment]
I have extracted the graphic, made the change and saved new graphic. 
[JOYSTICK.zip](https://github.com/a2-4am/4cade/files/5012093/JOYSTICK.zip)
I need help getting it packed (exomizer?) and combined with the test routine.

**Comment by peterferrie** [comment]
fixed in 670efc1a1d066236f980a5f98556a71e3835076b
