### ISSUE TITLE
Pac-Man crashes/hangs on startup

### ISSUE THREAD

**Issue by a2-4am** [a2-4am/4cade#322]
IIgs

**Comment by peterferrie** [comment]
Likely related to #286

**Comment by frankmilliron** [comment]
"The Games: Winter" and "Pac-Man" don't seem to have any effect with the CDA setting on or off. Pac Man worked on my ROM3 //gs either way. Winter did a reboot after practicing an event either way.

**Comment by peterferrie** [comment]
fixed in 33d00fc978e800c9ca3c5d20b44a27352d767620
