### ISSUE TITLE
No attract assets for Bejeweled

### ISSUE THREAD

**Issue by roughana** [a2-4am/4cade#326]
There is nothing displayed when the Flapple Bird or Bejeweled titles are selected and the user presses space for screenshots.

Dagen provided the original cover art. 
https://apple2infinitum.slack.com/files/U1J75A8PM/F012SS9N3AM/image.png?origin_team=T1J8S1LGH&origin_channel=C012AKTJY3S
This is better than the in-game title page because of a typo(!) on the title page.

**Comment by peterferrie** [comment]
Flapple Bird is in 3e7d87d7129bc86a3f14d759919c00468236329e
