### ISSUE TITLE
Quit back to GS/OS crashes on ROM3

### ISSUE THREAD

**Issue by frankmilliron** [a2-4am/4cade#327]
I can start TR from within GS/OS, but when using crtl-Q to quit back to GS/OS, it crashes to monitor.
Shows "X=0072 Y=0060 S=01F8 D=0000 P=71" and "00 M=00 Q=BE L=0 m=1 x=1 e=1".
Have tried several different disk images for GS/OS (6.0.1 and 6.0.4) and they all have the same problem.
Seems to be unaffected by the CFFA3000 //gs CDA setting.
ROM3 //gs

**Comment by peterferrie** [comment]
fixed in 33d00fc978e800c9ca3c5d20b44a27352d767620
