### ISSUE TITLE
Into the Eagle's Nest (4.0-alpha2) INFINITE LIVES fail (shooting ammo boxes / touching First Aid Kit)

### ISSUE THREAD

**Issue by michaela2kelsey** [a2-4am/4cade#333]
Bug originally DM'd to qkumba 8/23.  I was advised to open an issue.  

I only played the game a small amount in the 90's. AFAIK, the game only has one life per run.  TR lists it as Infinite Lives which I take to mean invulnerability. Now that the Infinite Lives makes game play possible, I discovered **Death by First Aid Kit**.

With Infinite Lives enabled, picking up a First Aid Kit performs instant kill. Shooting ammo boxes (which is surprisingly easy to do when accelerated) ends the game - something the game does without Infinite Lives / Invulnerability.  

Find any crate and open it (shoot it once) -- to find (1) nothing/empty (2) treasure (3) red dots = ammo.  If red dots, shooting it will trigger an ammo explosion giving instant death.  

To reproduce Death by First Aid Kit, see below. 

Steps (aka walkthrough) to reach the closest First Aid Kit.

1. Grab the key in initial room.
2. Unlock the silver door to the top of the room.
3. Exit room.
4. Move right.
5. Do not, yet, pick up green ammo.
6. Shoot yellow door to the top.
7. Enter room to the top.
8. Move left through passage until reaching key.
9. Grab key.
10. Turn around and double-back to ammo supply in previous room.
11. Grab ammo.
12. Return to previous room with key.
13. Turn right and move right until reaching locked silver door.
14. Approach door and the key will unlock it.
15. Continue right until reaching wall.
16. Head upward until reaching corner allowing left only or back the way you came.
17. Continue left, passing yellow door, until reaching alcove with ammo.
18. Grab ammo.
19. Head back to yellow door.
20. Shoot yellow door.
21. Enter room and grab key off to the right.
22. Exit back through the bottom door.
23. Head down until reaching wall.
24. Move left until reaching double-wide opening to bottom room.
25. Move down in to room.
26. Move right in the same room until reaching ammo.
27. Get ammo.
28. Turn 180 to face left.
29. Continue moving left until reaching locked door room with visible seated officer.
30. Expend key to unlock door.
31. Grab First Aid Kit in lower left region of room other side of officer's table.
32. Player spins and game ends with YOU ARE DEAD.

**Comment by peterferrie** [comment]
med kit is fixed in c1d555c5dfcaea232d211af32f6992e3cd994e7b.
Don't shoot the ammo boxes.
