### ISSUE TITLE
v4.0 alpha 3 doesn't work with Apple II High-Speed SCSI Card(?)

### ISSUE THREAD

**Issue by Shamus397** [a2-4am/4cade#339]
The reason that there's a question mark after the title of this bug is that it definitely *doesn't* work with an emulated A2HSSC (anecdote: it works fine with Pitch Dark), but I don't have the requisite real hardware to test with.  From what I can gather, it seems that Total Replay makes the assumption that ZP location $44 will remain zero through the HD boot process when it gains control of the system; however, the A2HSSC firmware sets it to 1 (at $CDA0, in bank 11 of the FW) just before loading block 1 off of the HD and transferring control to $801.  The fix is simple; set $44 to 0 before calling ProDOS.  :-)

Thought you might want to know.  :-)

Emulator used: http://shamusworld.gotdns.org/apple2/

**Comment by a2-4am** [comment]
Should be fixed in https://github.com/a2-4am/4cade/commit/b423cc2cdb87cdaa3aabe6c4fcc3fb7591db2aa4

**Comment by peterferrie** [comment]
It wasn't that TR was assuming $44 would be zero.  It was that I accidently forget to set it and therefore it was ununitialised.
It just so happened that everyone else leaves it as zero.  Otherwise I would have found it myself. :-)
