### ISSUE TITLE
Centipede crashes after a ridiculous sequence of steps

### ISSUE THREAD

**Issue by a2-4am** [a2-4am/4cade#340]
STR:

1. play game all the way through until GAME OVER
2. press RETURN 7 times (not fast, let it start the game then end the game then start the game then end the game, etc.)
3. game crashes

**Comment by peterferrie** [comment]
No repro for me in Virtual II.  If you could share a save-state just prior to it happening, then I can investigate.

**Comment by frankmilliron** [comment]
Can confirm it crashes in V2. Seems to hit a BRK showing "0003-    A=00 X=00 Y=00 P=37 S=F0" at the monitor.
You can replicate it without playing a game, by just slowly alternating between game and demo mode when hitting return.

**Comment by txgx42** [comment]
This instruction sometimes ends up jumping to $0000 and crashing

A432: 6C 24 04	JMP ($0424)

**Comment by peterferrie** [comment]
Okay, I can work with that.

**Comment by peterferrie** [comment]
Game bug.
