### ISSUE TITLE
Vindicator goes into demo mode at beginning of stage 5.

### ISSUE THREAD

**Issue by lukazi-2020** [a2-4am/4cade#342]
When playing the floppy disk image version of the game. At the start of level 5 it accesses the floppy disk. Have not investigated why it is doing the disk access. I suspect it may be reading information for the next set of levels.

**Comment by a2-4am** [comment]
Fixed in https://github.com/a2-4am/4cade/commit/168f90a16edcb232a3a653e190decd886beed9a4
