### ISSUE TITLE
Z-RAM Ultra 2/3 Clock invalid date after booting TotalReplay

### ISSUE THREAD

**Issue by cybernesto** [a2-4am/4cade#346]
TotalReplay modifies the date on the Apple //c Z-RAM Ultra 2/3 clock and sets it to invalid values that prevent ProDOS 2.4.2 from booting.

**Comment by peterferrie** [comment]
It's not on purpose.  How is the date being set?  Is it by writing to
a special memory address that we should be avoiding on the IIc?

**Comment by cybernesto** [comment]
The FastChip just happens to share the same addresses as the clock registers in the Z-RAM. See page 59 of [http://ae.applearchives.com/apple_c/z-ram_ultra_iii/z-ram_ultra_manual_11.pdf](url)
I propose a fix to skip the FastChip in the //c.

**Comment by peterferrie** [comment]
fixed in 1b90260631b64e57d1245f1abca635dd96eda460
