### ISSUE TITLE
Aztec crashes on launch (//e + Ultrawarp)

### ISSUE THREAD

**Issue by bobbimanners** [a2-4am/4cade#350]
Hardware config is //e Enhanced with Ultrawarp accelerator.

Regardless of whether Ultrawarp is disabled (with magic poke), Aztec crashes to a garbage text screen on start.  Beeps when it crashes.  Filenames are visible in the garbage text screen.  I will attach a screenshot.

![image](https://user-images.githubusercontent.com/11758908/98185690-23123900-1edb-11eb-9b52-68ad4b023f5a.png)

**Comment by peterferrie** [comment]
might be fixed by 1e7400e95669f7260930c7f85a1503612548f349

**Comment by bobbimanners** [comment]
Still fails, but now with `I/O ERROR` instead of screen of garbage.

**Comment by peterferrie** [comment]
fixed in 5b6a09c3b7b6a8e5403f8471e62b4970b0de4395
