### ISSUE TITLE
Build error after updated cadius to version 1.4.4

### ISSUE THREAD

**Issue by wyatt-wong** [a2-4am/4cade#354]
I got build errors after updated cadius to version 1.4.4. I am already using the latest source of 4cade. Please advise:

==================================================
wyattwong@MacBookPro 4cade % make
mkdir -p build/X build/FX build/PRELAUNCH build/GAMEHELP
touch build/log
acme -DBUILDNUMBER=`git rev-list --count HEAD` src/4cade.a 2>build/relbase.log
acme -r build/4cade.lst -DBUILDNUMBER=`git rev-list --count HEAD` -DRELBASE=`cat build/relbase.log | grep "RELBASE =" | cut -d"=" -f2 | cut -d"(" -f2 | cut -d")" -f1` src/4cade.a
for f in src/fx/*.a; do grep "^\!to" ${f} >/dev/null && acme ${f} >> build/log || true; done
bin/buildfileinfo.sh build/FX "06" "6000" >>build/log
for f in src/prelaunch/*.a; do grep "^\!to" ${f} >/dev/null && acme ${f} >> build/log; done
for f in res/TITLE.HGR/* res/TITLE.DHGR/*; do rsync --ignore-existing build/PRELAUNCH/STANDARD build/PRELAUNCH/$(basename $f); done
cp res/blank.hdv build/"4cade.hdv" >>build/log
cp res/_FileInformation.txt build/ >>build/log
cadius ADDFILE build/"4cade.hdv" "/TOTAL.REPLAY/" "build/LAUNCHER.SYSTEM" >>build/log
rsync -aP res/PREFS.CONF build/PREFS.CONF >> build/log
bin/padto.sh 512 build/PREFS.CONF >>build/log
188+0 records in
188+0 records out
188 bytes transferred in 0.001875 secs (100271 bytes/sec)
for f in res/TITLE res/COVER res/HELP res/GAMES.CONF res/ATTRACT.CONF res/FX.CONF res/DFX.CONF build/PREFS.CONF res/CREDITS res/HELPTEXT res/DECRUNCH res/JOYSTICK res/Finder.Data res/Finder.Root; do cadius ADDFILE build/"4cade.hdv" "/TOTAL.REPLAY/" "$f" >>build/log; done
bin/buildfileinfo.sh res/TITLE.HGR "06" "4000" >>build/log
bin/buildfileinfo.sh res/TITLE.DHGR "06" "4000" >>build/log
bin/buildfileinfo.sh res/ACTION.HGR "06" "3FF8" >>build/log
bin/buildfileinfo.sh res/ACTION.DHGR "06" "3FF8" >>build/log
bin/buildfileinfo.sh res/ACTION.GR "06" "6000" >>build/log
bin/buildfileinfo.sh res/ARTWORK.SHR "06" "1FF8" >>build/log
bin/buildfileinfo.sh res/ATTRACT "04" "8000" >>build/log
bin/buildfileinfo.sh res/SS "04" "4000" >>build/log
bin/buildfileinfo.sh res/ICONS "CA" "0000" >>build/log
for f in res/TITLE.* res/ACTION.* res/ARTWORK.* res/ATTRACT res/SS res/DEMO res/TITLE.ANIMATED res/ICONS; do cadius ADDFOLDER build/"4cade.hdv" "/TOTAL.REPLAY/$(basename $f)" "$f" >>build/log; done
cadius(25155,0x1190fadc0) malloc: *** error for object 0x7fb940000031: pointer being freed was not allocated
cadius(25155,0x1190fadc0) malloc: *** set a breakpoint in malloc_error_break to debug
/bin/sh: line 1: 25155 Abort trap: 6           cadius ADDFOLDER build/"4cade.hdv" "/TOTAL.REPLAY/$(basename $f)" "$f" >> build/log
/bin/sh: line 1: 25158 Segmentation fault: 11  cadius ADDFOLDER build/"4cade.hdv" "/TOTAL.REPLAY/$(basename $f)" "$f" >> build/log
/bin/sh: line 1: 25161 Segmentation fault: 11  cadius ADDFOLDER build/"4cade.hdv" "/TOTAL.REPLAY/$(basename $f)" "$f" >> build/log
/bin/sh: line 1: 25164 Segmentation fault: 11  cadius ADDFOLDER build/"4cade.hdv" "/TOTAL.REPLAY/$(basename $f)" "$f" >> build/log
/bin/sh: line 1: 25170 Segmentation fault: 11  cadius ADDFOLDER build/"4cade.hdv" "/TOTAL.REPLAY/$(basename $f)" "$f" >> build/log
cadius(25173,0x10d623dc0) malloc: *** error for object 0x7fc000747874: pointer being freed was not allocated
cadius(25173,0x10d623dc0) malloc: *** set a breakpoint in malloc_error_break to debug
/bin/sh: line 1: 25173 Abort trap: 6           cadius ADDFOLDER build/"4cade.hdv" "/TOTAL.REPLAY/$(basename $f)" "$f" >> build/log
/bin/sh: line 1: 25179 Segmentation fault: 11  cadius ADDFOLDER build/"4cade.hdv" "/TOTAL.REPLAY/$(basename $f)" "$f" >> build/log
/bin/sh: line 1: 25185 Segmentation fault: 11  cadius ADDFOLDER build/"4cade.hdv" "/TOTAL.REPLAY/$(basename $f)" "$f" >> build/log
cadius(25194,0x10fa69dc0) malloc: *** error for object 0x7f8785000031: pointer being freed was not allocated
cadius(25194,0x10fa69dc0) malloc: *** set a breakpoint in malloc_error_break to debug
/bin/sh: line 1: 25194 Abort trap: 6           cadius ADDFOLDER build/"4cade.hdv" "/TOTAL.REPLAY/$(basename $f)" "$f" >> build/log
for i in 1 2 3 4 5 6; do cadius RENAMEFILE build/"4cade.hdv" "/TOTAL.REPLAY/DEMO/SPCARTOON.${i}${i}" "SPCARTOON.${i}." >>build/log; done
cadius ADDFOLDER build/"4cade.hdv" "/TOTAL.REPLAY/FX" "build/FX" >>build/log
/bin/sh: line 1: 25209 Segmentation fault: 11  cadius ADDFOLDER build/"4cade.hdv" "/TOTAL.REPLAY/FX" "build/FX" >> build/log
make: *** [Makefile:46: dsk] Error 139
wyattwong@MacBookPro 4cade % 
==================================================

**Comment by digarok** [comment]
This looks like an issue with Cadius, not total replay.  Where did you get 1.4.4?  I recommend going back to an earlier version and seeing if that resolves your issue.  If so, report it to the Cadius team that you got your distro from (which is clearly not Brutal Deluxe based on your version number).

**Comment by wyatt-wong** [comment]
I downloaded the cadius source from https://github.com/mach-kernel/cadius and version 1.4.4 is need to build the Apple II Desktop below:

https://github.com/a2stuff/a2d/blob/main/docs/Building_And_Running.md

But using cadius 1.4.4 failed to build 4cade.

**Comment by peterferrie** [comment]
Please read our makefile.  The version to use comes from https://github.com/sicklittlemonkey/cadius
The bug that you are seeing is in Cadius not Total Replay.  Please open an issue with them instead if you will keep using that version.
