### ISSUE TITLE
Cosmetic issue for selecting games in TotalReplay

### ISSUE THREAD

**Issue by wyatt-wong** [a2-4am/4cade#356]
I booted up the TotalReplay build 2188 in Virtual ][, when I press "b" the game Boa bring up on screen, but when press right arrow key I found Apple Cider Spider was shown instead of the game that start with "b" follow after "Boa". I have made a video to show the issue.

https://user-images.githubusercontent.com/10095648/103099108-25298600-4648-11eb-82cc-5565f567832b.mov

**Comment by a2-4am** [comment]
Fixed in https://github.com/a2-4am/4cade/pull/357
