### ISSUE TITLE
Flight Simulator 2 - Spontaneous Reboot in Certain Locations

### ISSUE THREAD

**Issue by bobbimanners** [a2-4am/4cade#359]
I found a bug in the FS2 included in TR 4.0-rc1 ... it seems that there is a Bermuda Triangle.  Perhaps some of the scenery is missing.

For example if you use Fix Mode (hit Escape) to go to Boston Logan at 17899 North, 21853 East (Altitude 20) FS2 crashes immediately on returning from fix mode.  Also if you start out at (say) Igor I. Sikorsky Memorial and fly east, the sim crashes during flight (about 40NM from VOR Norwich on radial 080).  On both cases it reboots the machine.

I tried the copy of FS2 I have on floppy (also "Version 2.0") and I can go to Boston Logan without any issue.

**Comment by peterferrie** [comment]
fixed in bca5538536fe270058fb758f2ae9ac65155fd6ed
