### ISSUE TITLE
Bug in Spy Demise

### ISSUE THREAD

**Issue by jacexpo** [a2-4am/4cade#360]
Upon reaching level 5 - using the "cheat mode" of unlimited lives - the screen degenerates into a hires mess- and you can no longer play the game . It is as if the player and the elevators are working on different planes - each unaffected by what the other was doing, except overwriting each others screen presence. I would not be able to reach level 5 without the cheat code - therefore unknown whether the original image is the issue or the infinite lives introduced this problem. 
![Screen Shot 2021-01-10 at 3 51 12 PM](https://user-images.githubusercontent.com/31007691/104238103-1a803680-5427-11eb-9156-92e651568c43.png)

**Comment by jacexpo** [comment]
This is using the hdv image Total Replay v4.0-rc.1 - running on Virtual ][ Version 9.2 running on macOS Catalina.

**Comment by peterferrie** [comment]
fixed in 5a5dadcb1f4c8a8afad96657dabababc7564b4ee
