### ISSUE TITLE
Mr. Cool unlimited lives

### ISSUE THREAD

**Issue by xotmatrix** [a2-4am/4cade#362]
`4C47: EA EA EA `
I've been unable to create a working prelaunch from scratch without guidance. ¯\_(ツ)_/¯

**Comment by peterferrie** [comment]
> `4C47: EA EA EA `

We like to patch out the increments, too, in case the game isn't
prepared for >9 lives or whatever.

**Comment by xotmatrix** [comment]
`4C47: CE BC 5D  DEC  $5DBC   ; decrease lives of current player`
`562F: EE BC 5D  INC  $5DBC   ; increase lives of current player`

Lives are increased every 20000 points or when six fireballs are destroyed during "super cool time". If lives exceed 9 they are capped at 9 and another 10000 points are awarded. In a two player game, one player plays until a round is completed or their lives are exhausted.

Here are some key controls:
CTRL-C  End Game ($5986)
CTRL-R  Restart Game ($59AD)
CTRL-K  Use Keyboard ($59BB)
CTRL-J  Use Joystick ($59C7)
CTRL-S  Toggle Sound ($59D3)
CTRL-I  Initialize Game Settings ($59E2)

Bug: Selecting "Teddy Bear" mode changes some initial values ($9097 halves fireball speed but also affects RNG?). Answering "N" when asked if selections are OK will restart the configuration but not reset the teddy bear settings. 

Atari instructions here:
http://www.atarimania.com/game-atari-400-800-xl-xe-mr-cool_3566.html

**Comment by xotmatrix** [comment]
I figured out how to get it to work by tracing the decompression routine. I hope I got it right. I tried all sorts of wrong things until I worked out what was really supposed to happen. Is there an easier way to find the magic numbers?

**Comment by peterferrie** [comment]
The patch looks good.
The magic numbers being the places to change?  No, no easy way to find them.
The decompression routines need to be traced to find where to exit,
and the multi-loaders make that even harder.
For finding the cheat places like timers, I tend to use an emulator to
watch for writes to the screen locations that show the values, and
then see who requested the write.
For lives, a before- and after- save-state usually works.

**Comment by xotmatrix** [comment]
I meant finding entry/exit points to interrupt the decompressor with a patch. OK. It will be easier next time.
