### ISSUE TITLE
Berzap!'s speech not working (SSI263)

### ISSUE THREAD

**Issue by tomcw** [a2-4am/4cade#373]
My setup:
- Total Replay v4.01.hdv
- AppleWin 1.29.16.0 (latest release)
- Either Mockingboard in slots 4&5 or Phasor in slot-4

When I start TR, it reports "and it talks!"

For Berzap!, I boot it and from the title screen (ignore "Ctrl-C to change controls") and just hit RETURN to immediately start the game, then I get no speech, and after losing all 3 lives, it hangs at a static image of the talking head. NB. I do get Mockingboard music.

If instead I boot and at the title screen I press Ctrl-C (where I can see that Mockingboard-C is pre-selected), and **just immediately exit** (with RETURN), then starting the game (RETURN again) I now get SSI263 speech.

**Comment by peterferrie** [comment]
fixed in 705de21e63217d477d6e8def31b14aeed4355458.
