### ISSUE TITLE
compiling on windows

### ISSUE THREAD

**Issue by acidrain97** [a2-4am/4cade#374]
downloaded the recommended windows software, ran winmake.bat dsk following error:

fatal: not a git repository (or any of the parent directories): .git
Error in CLI arguments: Could not parse 'BUILDNUMBER='.

It compiles but when loaded in applewin, crashes (goes to the monitor)

Can someone help with this?

Thanx

**Comment by peterferrie** [comment]
It can't build if it's downloaded as a .zip.  It needs to be cloned via GitHub or similar so that the commit history is brought down, too.

**Comment by acidrain97** [comment]
Finally got it to compile. My apple //e loves it. thanx
