### ISSUE TITLE
Bouncing Kamungas & Thunder Bombs don't pre-configure to enable Mockingboard speech/sound

### ISSUE THREAD

**Issue by tomcw** [a2-4am/4cade#375]
My setup:
- Total Replay v4.01.hdv
- AppleWin 1.30.1.0 (latest release)
- Either Mockingboard in slots 4&5 or Phasor in slot-4

Both these games require a hidden CTRL+S menu to select the Mockingboard type+slot before speech/sound will work with them.

The TR pre-launch should auto-select this if the Mockingboard h/w is available.

**Comment by peterferrie** [comment]
Apple Cider Spider is also on that list.
I've been meaning for ages to fix that.  A task for v5.

**Comment by tomcw** [comment]
I see... for that one it's: CTRL+B

**Comment by peterferrie** [comment]
Fixed by bb85aee3662bc7037ea9803ed6576a55b68fac6e, 3cca3b36a72f23d0ee7c2d842473a1b3291b436f,  93617432a3430c8af1f460a9637c0d43083fb6cf
