### ISSUE TITLE
High Score storage

### ISSUE THREAD

**Issue by roughana** [a2-4am/4cade#44]
Given that qkumba's ProDOS ports usually (? / sometimes?) include a mechanism to save the high scores and load them from a file, I was expecting this to also be possible within Total Replay. It doesn't appear to be. Can this be done?

**Comment by a2-4am** [comment]
AFAIK, every game that originally could save its own high scores on the original disk, can save its own high scores within Total Replay. Scores are saved and loaded in files in each game's directory.

Is there a specific game where you expected high scores to be saved and they are not?

**Comment by roughana** [comment]
Ah, the pertinent point is probably "that originally could save its own high scores on the original disk". Although if there is a high score table, I'd expect that it would be able to have been saved. I'll take careful notes from now on.

**Comment by peterferrie** [comment]
All games that could save before being ported do save after being ported. I
have not missed any.
However, there are a number of games (Star Blazer, Buck Rogers, etc) which
display a high score that exists only in memory. I did not add the
functionality to save those scores. You'll just have to take a picture.

**Comment by roughana** [comment]
Apple Cider Spider has an option to erase high scores, but does not appear to store them to disk. I'm not sure what the original functionality was.

**Comment by peterferrie** [comment]
> Apple Cider Spider has an option to erase high scores, but does not appear
> to store them to disk. I'm not sure what the original functionality was.

The in-memory copy is zeroed, to support the rage-quit when your
brother beats your score.

**Comment by peterferrie** [comment]
I'm wrong after all.  Apple Cider Spider does indeed save its high scores (CIDER.SPIDER.Z).  There was a bug when writing to files < 512 bytes.  It's fixed now.

**Comment by roughana** [comment]
ACS and Lancaster high scores are stored and retrieved in Total Replay 2 beta2.
