### ISSUE TITLE
winmake dsk produce a broken hdv

### ISSUE THREAD

**Issue by Mark-Five** [a2-4am/4cade#442]
Building using make on a Mac works fine.
When using winmake.bat under windows, it creates a broken hdv image.

**Comment by xotmatrix** [comment]
At least three others including myself have experienced this apparent file system race condition. A second run may build an image that boots using index files generated during the previous build. However, I have questions about how reliable this might be if those files are open during the second build. Potentially, the data in them would be the same but it seems risky. If those indices are from an earlier build/commit number, that seems like a big problem.

**Comment by Mark-Five** [comment]
Just tried to build it a second time and it actually works. That's a cool workaround for me as my only Mac is pretty old and is still running High Sierra and it'll eventually be unsupported.

**Comment by peterferrie** [comment]
"winmake clean" will remove all traces (the entire build directory is removed), but it also requires that you wait a few seconds afterwards before you try to build.  Eventually, I will work out the exact cause, but I haven't succeeded yet.

**Comment by xotmatrix** [comment]
The generated files are not all the build directory.
```
        modified:   src/index/artwork.idx.a
        modified:   src/index/attract.idx.a
        modified:   src/index/cache00.idx.a
        modified:   src/index/cache01.idx.a
        modified:   src/index/cache10.idx.a
        modified:   src/index/cache11.idx.a
        modified:   src/index/coverfade.idx.a
        modified:   src/index/credits.idx.a
        modified:   src/index/decrunch.idx.a
        modified:   src/index/dfx.idx.a
        modified:   src/index/dhgr.idx.a
        modified:   src/index/dtitle.idx.a
        modified:   src/index/fx.idx.a
        modified:   src/index/gamehelp.idx.a
        modified:   src/index/gr.fizzle.idx.a
        modified:   src/index/gr.idx.a
        modified:   src/index/helptext.idx.a
        modified:   src/index/hgr0.idx.a
        modified:   src/index/hgr1.idx.a
        modified:   src/index/hgr2.idx.a
        modified:   src/index/hgr3.idx.a
        modified:   src/index/hgr4.idx.a
        modified:   src/index/hgr5.idx.a
        modified:   src/index/hgr6.idx.a
        modified:   src/index/joystick.idx.a
        modified:   src/index/miniattract.idx.a
        modified:   src/index/prelaunch.idx.a
        modified:   src/index/res.cover.idx.a
        modified:   src/index/res.help.idx.a
        modified:   src/index/res.title.idx.a
        modified:   src/index/search00.idx.a
        modified:   src/index/search01.idx.a
        modified:   src/index/search10.idx.a
        modified:   src/index/search11.idx.a
        modified:   src/index/shr.fizzle.idx.a
        modified:   src/index/slideshow.idx.a
        modified:   src/index/title.idx.a
```

**Comment by wyatt-wong** [comment]
> Just tried to build it a second time and it actually works. That's a cool workaround for me as my only Mac is pretty old and is still running High Sierra and it'll eventually be unsupported.

I remembered at one time I built 4cade under macOS (I couldn't remembered I was using Mojave or Cataliina at that time) and the generated HDV have some problems (I didn't recall if it was unable to boot up or certain game crashed or something else). After I deleted the whole 4cade folder from my Mac and then clone it again, I was able to build the HDV file successfully in macOS.

I seldom using winmake.bat in Windows so I was unaware that a broken HDV will be created using winmake.bat

**Comment by peterferrie** [comment]
> The generated files are not all the build directory.
> ...

Yes, but they are all generated from files that are placed in the
build directory first.
Hence, cleaning the build directory completely leads to good index files.
