### ISSUE TITLE
Apple II+ and "Columns" game shows corrupt title screen & crashes on attempting to start it

### ISSUE THREAD

**Issue by tomcw** [a2-4am/4cade#444]
From the attract-mode screenshots, it looks like this game supports both HGR (for II+) and DHGR (//e, IIgs) versions.
But on a II+, I see a corrupt title screen & the game crashes when I try to start it.

Repro:
- AppleWin 1.30.7.0
  - set model=Apple II+, and disable VidHD
- Use: TR build 3120  (4am's build attached to Slack on 2021-12-20)
- Type "COL" and you'll get a purple/green/white title screen (ie. the DGHR screen, but shown as HGR, since DHGR isn't available on a II+)
- Hit RETURN to play, and (if stepping in the built-in debugger, with `brk all on`) then it'll trap in the debugger at $DBB7 due to an invalid opcode

Corollary: would this game work in DHGR on a II+ with a VidHD?
(I assume this is out of scope: an Apple II+ with VidHD just extends things for SHR box art, not for DHGR games.)

**Comment by xotmatrix** [comment]
Same screenshot problem with Bruce Lee, Tetris, and Thexder. Tetris also fails to run correctly. Reproduced in MAME 0.237. 

Apparent regression between 2814 and 2918. Wish I could be more precise.

**Comment by a2-4am** [comment]
Columns crash-on-launch is fixed in https://github.com/a2-4am/4cade/commit/e8d3aabd401d7622ec3875cd892eea78f10d0b8e

**Comment by a2-4am** [comment]
@peterferrie please sync `winmake.bat`

**Comment by a2-4am** [comment]
DHGR games are unlikely to work on 64K+VidHD. Even if they never run code from auxmem, they would assume they can store actual data in auxmem AND not have those writes actually clobber mainmem. The game would have to be specifically coded with those restrictions in mind, much like our SHR transition effects are. I would be shocked if any DHGR game worked under those conditions.
