### ISSUE TITLE
The Chase on Tom Sawyer's Island crashes on startup

### ISSUE THREAD

**Issue by frankmilliron** [a2-4am/4cade#446]
ROM 1 and ROM 3 //gs crashes on attempting to start 'The Chase on Tom Sawyer's Island'.

**Comment by frankmilliron** [comment]
![Screen Shot 2021-12-26 at 10 27 01 PM](https://user-images.githubusercontent.com/34376619/147441383-09796bec-189f-48c3-8f98-1de9b562c478.png)

**Comment by frankmilliron** [comment]
Does not start on //e, either.

**Comment by peterferrie** [comment]
fixed in 5069c95a4b4d531ee82128b5b9ad1258a9b6663c
