### ISSUE TITLE
Lores screenshots not working

### ISSUE THREAD

**Issue by frankmilliron** [a2-4am/4cade#45]
Total Replay seems to go into an endless loop trying to load a lores screenshot, after pressing the space bar. Tried with blockchain and pollywog (the only 2 lores-based games, afaik).

**Comment by peterferrie** [comment]
fixed in fa6a014c7764f74975d590bd4ede8c2362fdf8e1

**Comment by frankmilliron** [comment]
good news that OOTW will be added. just checked that out!
