### ISSUE TITLE
Distinguish detected speech between SC01 and SC02

### ISSUE THREAD

**Issue by roughana** [a2-4am/4cade#457]
When TR4 Bouncing Kamungas is loaded in AppleWin it does not have the MB Speech configured. The attract mode says "The Bouncing Kamungas" frequently when it is configured correctly.

Ctrl-S accesses MB setup within the game. Options are 
1. Apple Speaker
2. No Sound
3. Sound 1
4. Sound 2
5. Speech 1 
6. Sound / Speech 1

If an SC01 has been detected then it should be configured as Sound / Speech 1.
If an SC02/SSI263 has been detected then it should be configured as Sound 2, because the SC02 usage is different to SC01 usage and SC01 speech is not supported on SC02.

TR detects speech, but it does not distinguish between SC01 and SC02.
The titles that support speech support one or the other (except for Berzap which supports both).

**Comment by roughana** [comment]
AppleWin may actually detect for both SC01 and SC02 which would make it confusing.
Rob Justice has also been working on a daughtercard for the MB that allows the SC01 to be used in a regular MB that may also support SC02.
Therefore would be good to detect between the two and choose the right setting for the game.

**Comment by peterferrie** [comment]
done in 0c12457e69bc90582b16e9d7ef44f0d1426c2ca9.  The affected games need testing on hardware.
