### ISSUE TITLE
couple issues with new Conan demo

### ISSUE THREAD

**Issue by frankmilliron** [a2-4am/4cade#459]
`res/demo/_FileInformation.txt` should be set to $200. Demo doesn't run currently as it's set to $300.

Also, the call to `jsr   $5FF8      ; decompress` in `src/demo/conan.a` ends up changing the reset vector to $C600. Can we change this back to point at $100? I tried to fix it, but there must be a checksum on it, as the first demo screen is missing the blue boxes at the bottom if you tamper with it.

Goonies runs great however!

**Comment by peterferrie** [comment]
fixed in f271c1fd649c57b5b53b3f698a0c7d1eae38bfec and 8e6f33b9515a4e0e49db94d44985fded1d59c7ae.
