### ISSUE TITLE
Which two original game disks is 4am missing?

### ISSUE THREAD

**Issue by xandark** [a2-4am/4cade#46]
I saw the [Kansasfest video presentation](https://www.youtube.com/watch?v=pki7rsGNxXs) and it was said that there are just two original disks that 4am does not have to make a clean crack. 

Could you state which games those are so that maybe the community can keep their eyes out to get to 4am? And the flip-side of this is, which two games on the compilation are from older cracks?

**Comment by a2-4am** [comment]
- Mario Bros.
 - Crystal Castles

Neither was officially released.
