### ISSUE TITLE
softSP compatibility

### ISSUE THREAD

**Issue by tynbendad** [a2-4am/4cade#460]
couldn't total replay be made to work with softSP (e.g., for the ][+ with floppyemu|wdrive) just by avoiding re-using the addresses softSP is using? (no, i don't know what addresses those are or what to change in total replay...)

**Comment by peterferrie** [comment]
As I understand it, the issue is not the softSP, it's the wDrive, and only with certain titles.  I will investigate a bit more.

**Comment by tynbendad** [comment]
Hmm, i have a wdrive but can't even get to the total replay menu with it.

**Comment by chris-torrence** [comment]
I have the wDrive with v2.0b01, SoftSP, and Total Replay v5.0-alpha.1. On my machine (enhanced IIe, Mockingboard slot 4), Total Replay boots about half of the time. The other times it either crashes with an I/O Error or starts to boot but then crashes to the monitor. If it does start successfully, then I am able to start up most games, including Thexder. So something still isn't quite right but it's getting better.

**Comment by tynbendad** [comment]
Fwiw I have ][+ (64k, wdrive, no sp card), and every time I power up total replay 5alpha1 will go to monitor as in pic..
![20220525_113302](https://user-images.githubusercontent.com/20666529/170328227-1cb95fd9-4c72-4c51-b4ac-111d72c4ced0.jpg)

**Comment by wyatt-wong** [comment]
Please raise your question to Mfa2 Workshop in Facebook.

Best Regards,
Wyatt Wong 

    On Thursday, May 26, 2022, 01:39:23 AM GMT+8, tynbendad ***@***.***> wrote:  
 
 


Fwiw I have ][+ (64k, wdrive, no sp card), and every time I power up total replay 5alpha1 will go to monitor as in pic..

**Comment by chris-torrence** [comment]
I just tried this again with the SoftSP card, and it seems to work fine. I booted the computer like 10 times in a row with no issues. wDrive v2.0b01, SoftSP card in slot 1, Mockingboard in slot 4, CH joystick, and Total Replay v5.0-alpha.1.

**Comment by peterferrie** [comment]
I wonder if random boot failures are related to power consumption or shorting somewhere.  In any case, I don't see it as a software issue.  We initialise all memory that we read.

You don't need the SoftSP to boot TR anyway.  The wDrive can do it by itself.
