### ISSUE TITLE
Artesians fails to launch properly if you press a key during decompression

### ISSUE THREAD

**Issue by a2-4am** [a2-4am/4cade#461]
<img width="1436" alt="Screen Shot 2022-05-20 at 11 38 22 AM" src="https://user-images.githubusercontent.com/22437310/169563256-6f293d76-86b8-490e-b2be-eec0dafdfab4.png">

**Comment by frankmilliron** [comment]
It's hitting the keypress check subroutine at $B400 without clearing the strobe and unpack ends up going off the rails.

**Comment by peterferrie** [comment]
It doesn't enable hires mode, which we set to lores as a side-effect of clearing the text screen.  Fixed in ea8105ec821e1d7f876dd39a50273f24b42d3b3d
