### ISSUE TITLE
Galactic Attack displays error message on reset

### ISSUE THREAD

**Issue by a2-4am** [a2-4am/4cade#463]
<img width="1436" alt="Screen Shot 2022-05-20 at 11 52 38 AM" src="https://user-images.githubusercontent.com/22437310/169565836-9be44389-a3d6-4117-ac8f-83fa87771412.png">

**Comment by a2-4am** [comment]
I pressed reset at the "what type of game" prompt

**Comment by frankmilliron** [comment]
Overwrites reset hook at $100

**Comment by peterferrie** [comment]
fixed in 15aadcae81077b9f5810ac02ad2c73fda5734238
