### ISSUE TITLE
Microwave

### ISSUE THREAD

**Issue by cskare** [a2-4am/4cade#470]
Microwave hangs after level 6.

**Comment by peterferrie** [comment]
I can't reproduce this in AppleWin.
Is it hanging for you on hardware or in an emulator?
If hardware, which one?  If emulator, which one?

**Comment by cskare** [comment]
This happens in emulator AppleWin 1.30.9.0 with cheats enabled Enhanced Apple //e and PC Joystick #1.

**Comment by cskare** [comment]
I tried again, andt this time it hanged after level 8.

**Comment by peterferrie** [comment]
Please share a save-state after the hang occurs.

**Comment by cskare** [comment]
[Total Replay v5.0-alpha.1.zip](https://github.com/a2-4am/4cade/files/8759588/Total.Replay.v5.0-alpha.1.zip)

**Comment by peterferrie** [comment]
Not the drive image.  Press F11 to save the memory-state, then please attach the resulting .aws file.

**Comment by cskare** [comment]
Sorry about that.  Try this...
[Total Replay v5.0-alpha.1.aws.zip](https://github.com/a2-4am/4cade/files/8759749/Total.Replay.v5.0-alpha.1.aws.zip)
.

**Comment by peterferrie** [comment]
Thanks, I see it now.  It's a bug in the game that I will fix.
