### ISSUE TITLE
Berzap! infinite SC01 speech phonemes after selecting MB-C on AppleWin

### ISSUE THREAD

**Issue by tomcw** [a2-4am/4cade#479]
Repro, under AppleWin: (*)

TR v5.0-alpha.1  (either Phasor in s4; or MB in s4+s5)
(but also the same with TR 4.01)
- Choose: Berzap!
- TR automatically picks: MB Sound/Speech
- CTRL-C, Left Cursor, SPACE to pick: MB C  (and press RETURN)
- Now you'll get repeating SC01 phonemes

See [here](https://github.com/AppleWin/AppleWin/issues/1105#issuecomment-1140448934) for details of the problem.
Or TL;DR: On selecting MB-C, the game should write $C40C = 0.

(*) AppleWin's Mockingboard (and Phasor) cards offer both SSI263 (SC02) and SC01 speech chip support.

NB, potentially in the future this won't just be limited to AppleWin...
In #457, @roughana said [here](https://github.com/a2-4am/4cade/issues/457#issuecomment-1108495496):

> Rob Justice has also been working on a daughtercard for the MB that allows the SC01 to be used in a regular MB that may also support SC02.

**Comment by peterferrie** [comment]
fixed in 6b703323c04cf21e0012445e18a8576d35149f92
