### ISSUE TITLE
Press a letter key and then press left arrow will return to main screen

### ISSUE THREAD

**Issue by wyatt-wong** [a2-4am/4cade#48]
After I started TotalReplay and then press a letter key (e.g. W) and then if I press left arrow key, it will go back to the main screen instead of to the last game that starts with letter V. If I press the right arrow key after pressing a letter key (e.g. W), then it will be fine.

**Comment by peterferrie** [comment]
This is expected behaviour.  The left arrow in search mode functions like the Delete key, to remove characters from the search.  When the search is emptied, TR returns to the main screen.  Try pressing V twice and then pressing the left arrow to see it more clearly.

**Comment by wyatt-wong** [comment]
Expected behavior? Then how do I “clear” the character after I pressed a letter key ?

**Comment by a2-4am** [comment]
In search mode, Left arrow or backspace will remove 1 letter. Escape will remove all letters and return to the title screen.
