### ISSUE TITLE
No boot on Apple //c with AE Z-RAM Ultra 3

### ISSUE THREAD

**Issue by cybernesto** [a2-4am/4cade#483]
version 5.0-alpha.3 does not boot on my Apple //c with a [Z-RAM Ultra 3](http://ae.applearchives.com/apple_c/z-ram_ultra_iii/) card installed in it. It only shows some random characters on screen right after displaying TOTAL REPLAY. It is not possible to drop into the monitor with a soft reset.

I have installed the 65C816 processor option, so this might be a reason why it is confusing the SW. Total Replay 4 works fine in this setup though, so it must be something in version 5.

**Comment by mgcaret** [comment]
There is a case where software may accidentally enable the Z80 on the card, which is turned on by a write to the $C4XX space. The Mockingboard 4c, for instance, requires activation by writes to $C403 and $C404. If the Z80 is activated without proper Z80 code in place at $1000 after a reset, it will likely crash.

**Comment by mgcaret** [comment]
If it's accidentally enabling the Z80, the culprit is here: https://github.com/a2-4am/4cade/blob/main/src/hw.mockingboard.a#L37-L38

This can be solved by loading a small Z80 routine at $0FFC (FFFCh in the Z80 space): $32 $00 $E4 $C3 FC FF which is

```
LD (E400h),A ; card is at $E4000 due to memory translation
JP  FFFCh
```

This will return the system to 6502 mode and leave it in the same state as the Z80 after RESET: ready to execute the instruction at 0000h (from the Z80 perspective).

**Comment by peterferrie** [comment]
Can the presence of the Z80 be detected from the Apple II side?
Can the Apple II write into the Z80 space?
If yes and yes, then I can add that program to the MB initialisation code.

**Comment by mgcaret** [comment]
Yes and yes.

For a Softcard-style Z80 card, which is what the Z-RAM Ultra III is, the Z80 and Apple II share the same memory space, with address translation on the Z80 changing it's view a bit.  So writing to Z80 memory is simply writing to the Apple II memory keeping that translation in mind.

The only way to detect it is to put Z80 code at $1000 ($0000 in the Z80) and attempt to activate the Z80.  Detection involves having the Z80 change a location in memory.  For this case you (probably) don't really want to detect it, just make it not crash the machine when attempting to activate a Mockingboard IIc.  Just putting the 6 bytes I mentioned above at $0FFC (it's at $FFFC from the Z80 view) will do the trick, immediately turning it off and resuming execution of the 6502.  The reason for those 6 bytes being at that location is that it will survive multiple attempts to activate the Z80, and will leave the Z80 in a good state if the user decides to boot CP/M next without a reset.

If you really want to detect it, some code I wrote to do so is here: https://github.com/a2stuff/a2d/blob/main/desk.acc/this.apple.s#L544-L554

**Comment by cybernesto** [comment]
> There is a case where software may accidentally enable the Z80 on the card, which is turned on by a write to the $C4XX space. The Mockingboard 4c, for instance, requires activation by writes to $C403 and $C404. If the Z80 is activated without proper Z80 code in place at $1000 after a reset, it will likely crash.

Yep, I can confirm that commenting out these writes fixes the issue on my configuration.

**Comment by peterferrie** [comment]
Okay, now I understand the requirement.  Yes, I don't need to detect.  Thanks MG.  I will make this change.

**Comment by peterferrie** [comment]
[LAUNCHER.zip](https://github.com/a2-4am/4cade/files/9742535/LAUNCHER.zip)
Please try this.

**Comment by cybernesto** [comment]
> [LAUNCHER.zip](https://github.com/a2-4am/4cade/files/9742535/LAUNCHER.zip)
> Please try this.

No, that did not work. A bunch of ;@ are printed on the screen. It works on the emulator though.

**Comment by peterferrie** [comment]
@mgcaret should it be 7 bytes starting with a 0 at FFC?  Otherwise, the JP starts at FFF and then the instruction at 0 is a CALL, and we see the screen full of ;@.

**Comment by mgcaret** [comment]
No, I’m just suffered some sort of cognitive impairment in the form of an off-by-one error.

It should be at $0FFD and be $32 $00 $E4 $C3 $FD $FF…

**Comment by peterferrie** [comment]
[LAUNCHER.zip](https://github.com/a2-4am/4cade/files/9749262/LAUNCHER.zip)
cool, let's try that.

**Comment by peterferrie** [comment]
Does this mean that the code at $FFD has to remain in place forever, if the Z80 won't be used intentionally, but might be activated by a game assuming the presence of a Mockingboard and writing into $C4XX?

**Comment by peterferrie** [comment]
[LAUNCHER.zip](https://github.com/a2-4am/4cade/files/9749288/LAUNCHER.zip)
anyway, let's see if this boots.

**Comment by mgcaret** [comment]
Yeah, games that assume the presence of a mocking board might be a problem.  If they attempt to write to the region that activates the Z80, it will likely cause a hang or crash.  The ones in the Mockingboard 4c manual’s list of games that automatically activate it are candidates for bad behavior.  Games that read the area looking for the VIA’s timers first before deciding to write are probably okay. 

As far as a solution goes, you could leave that Z80 code in place if possible, or perhaps go through with detection and patch affected games at launch time.  Whether either of these options  is easy or practical, however…

**Comment by peterferrie** [comment]
I have patches now for programs that assume the MB is in slot 4, so I can extend those to disable MB support.

**Comment by cybernesto** [comment]
> [LAUNCHER.zip](https://github.com/a2-4am/4cade/files/9749288/LAUNCHER.zip)
> anyway, let's see if this boots.

this one boots, but does not work correctly. Pressing the right arrow shows a corrupted screen and it hangs.
BTW I tested Skybox and Zaxxon and they do not hang my system.
Do you know why the MB 4c requires these writes? I would have expected it to work like a normal MB and the SW requiring patches do so because they were detecting the 2c and skipping the music playback.

**Comment by peterferrie** [comment]
According to the manual, the writes are required to active slot 4 so that the MB 4c will know to start listening.
Without those writes, sometimes the MB 4c won't respond and then won't be detected.

**Comment by mgcaret** [comment]
The writes are because the IIc has firmware in “slot” 4.  In a pre-V3 ROM, it’s the mouse firmware.  In a V3+ machine, it’s the RAM disk for the memory expansion card.  Activating the MB 4c will cause the firmware for the respective device to be unusable when it takes over.  For the mouse it’s probably not a big deal, but for the RAM disk, if the system has already initialized one it might cause problems.  Part of the boot process in V3+, for instance, jumps straight to $C400.

**Comment by peterferrie** [comment]
That it boots shows that the Z80 fix gets us partway there, but I'm guessing that the accelerator functions are triggering another issue somehow.  I don't see the $FFD-1002 region being overwritten so it's something else.

**Comment by mgcaret** [comment]
You’re welcome!  It’s nice to be able to make a small contribution, life has interfered with my Apple II hobby as of late.

**Comment by peterferrie** [comment]
Thank you both for the help.  The Yellowstone issue is not solved with this change, but that's for another day.
