### ISSUE TITLE
Compiling error 

### ISSUE THREAD

**Issue by DarthSabbath** [a2-4am/4cade#486]
'git' is not recognized as an internal or external command,
operable program or batch file.
Error in CLI arguments: Could not parse 'BUILDNUMBER='.
'chdman' is not recognized as an internal or external command,
operable program or batch file.

**Comment by peterferrie** [comment]
"rem third-party tools required to build (must be in path)"
You will need to install a Git client, at the least.  See Github.com for instructions.
There's no need anymore to produce a CHD version.  MAME can load the HDV directly now.
