### ISSUE TITLE
Crashes on boot with Dan ][ Sd Card Reader.

### ISSUE THREAD

**Issue by dabonetn** [a2-4am/4cade#488]
I've built a couple of these Prodos emulators.

https://github.com/profdc9/Apple2Card

Trying to boot the Total Recall v5 image crashes to the monitor right after the TOTAL RECALL text in the middle of the screen.
Screen has 
2043-        A=9B X=00 Y=00 P=B5 S=F9

Loading a Prodos image that boots to Bitsy Bye, I can swap another card on D7,2 and load LAUNCHER.SYSTEM it runs fine.

Any suggestions?

**Comment by peterferrie** [comment]
If you're willing to run some tests for me, then I am willing to make them.  I'll also have some questions about how the hardware presents itself to software.

**Comment by frankmilliron** [comment]
proboothd : readdone jmp   $203b ??

**Comment by frankmilliron** [comment]
dabonetn are you using block mode or FAT mode? Are you trying to boot from S7,D2? or S7,D1?

**Comment by dabonetn** [comment]
Always trying to boot S7,D1, either fat or block mode.

**Comment by dabonetn** [comment]
""If you're willing to run some tests for me, then I am willing to make them. I'll also have some questions about how the hardware presents itself to software.""

I'm willing to run the tests, as for how the device presents itself, I'm not sure. I'm not the developer. But the source code for the apple firmware and atmega328 code is on the project github I linked.


But I am willing to ship a spare unit to one of the contributors for troubleshooting if needed. (Hopefully in the USA)

**Comment by frankmilliron** [comment]
The card is using $00FE and $00FF for temp storage. Unfortunately, these locations are also used by proboot.

**Comment by dabonetn** [comment]
Any suggestions on a safe couple of bytes in zero page?

**Comment by frankmilliron** [comment]
$FC and $FD? Proboot only uses $FE and $FF. Most of $90 to $FE is unused but I'm not an expert in what ProDOS will want to use. Also, One of the locations is being used as a 'knownRTS'. The A2 ROM already has a 'known RTS' at $FF58.

**Comment by frankmilliron** [comment]
dabonetn, no need. The firmware for the card has been updated and tested. Should work perfectly with Total Replay now. Variable has been moved to $FD and the new SYSTEM file to flash the firmware is available on the github repo.

Issue can be closed.

**Comment by dabonetn** [comment]
Just out of curiosity, how did it get patched this quick? Did someone email profdc9?
Not that I'm complaining.. But that was quick!

**Comment by frankmilliron** [comment]
I opened an issue and profdc9 patched it right away once I explained where it was going off the rails.


On Jul 26, 2022, at 2:38 PM, dabonetn ***@***.***> wrote:

﻿

Just out of curiosity, how did it get patched this quick? Did someone email profdc9?
Not that I'm complaining.. But that was quick!

**Comment by peterferrie** [comment]
Super.
