### ISSUE TITLE
Sneakers graphics glitch

### ISSUE THREAD

**Issue by xotmatrix** [a2-4am/4cade#49]
The Sneakers graphics glitch has somehow slithered its way into the v2.0 release.

![Applewin_2019-09-14_12-53-55](https://user-images.githubusercontent.com/14209329/64911356-b93f3a80-d6ee-11e9-8f86-ccfc8fdc17d7.png)
![Applewin_2019-09-14_12-52-57](https://user-images.githubusercontent.com/14209329/64911347-9ca30280-d6ee-11e9-9c50-4cd38b2ec4d0.png)

**Comment by peterferrie** [comment]
Fixed in 282156cdcd09c66a29857ad0b1866f7754419eb8
