### ISSUE TITLE
Neu] [ower: Boss key is broken

### ISSUE THREAD

**Issue by jeremypenner** [a2-4am/4cade#491]
Steps to reproduce:
Load Neu] [ower, skip past the dialog, and press Ctrl-B to bring up the boss key

Expected behaviour:
The game switches to text mode, where a fake spreadsheet is displayed.

Actual behaviour:
The game switches to text mode, which is filled entirely with the number 2.

(Spoiler: This makes the game unwinnable in a very frustrating way)

**Comment by a2-4am** [comment]
confirmed fixed via MAME 0.245 ROM03 emulation
![image](https://user-images.githubusercontent.com/22437310/181776003-bb634627-9e44-465c-ac84-39f76884470a.png)
