### ISSUE TITLE
Receive compilation warnings on Parallel

### ISSUE THREAD

**Issue by wyatt-wong** [a2-4am/4cade#496]
When I build the 4cade from source to binrary under macOS, I frequently receive the warnings from "Parallel" as follows:

![image](https://user-images.githubusercontent.com/10095648/186289584-1b1a11fe-02db-494e-b009-efc13bb5e9c3.png)

**Comment by micahcowan** [comment]
Wyatt, according to that message, if you run `parallel --citation` once, you'll never see that message on that machine again. Hope that helps!

**Comment by wyatt-wong** [comment]
> Wyatt, according to that message, if you run `parallel --citation` once, you'll never see that message on that machine again. Hope that helps!

I already saw that and tried yesterday but it just gave me a bunch of messages. But I have to check again to make sure I type "parallel --citation" instead of "parallel -citation"....

**Comment by peterferrie** [comment]
Regardless, this is not an actual issue with Total Replay.  Closing.
