### ISSUE TITLE
Self-running demos hang on older CFFA card?

### ISSUE THREAD

**Issue by frankmilliron** [a2-4am/4cade#50]
I have a ][+ with an older, non-3000 CFFA card in it. On several of the self-running demos, the system hangs. Affects Conan, Apple Cider Spider, and some other which I can't tell because it hangs on a black screen. Using "Total Replay v2.0-beta2.2mg".

**Comment by peterferrie** [comment]
I haven't reproduced it using the CFFA2 in MAME.

**Comment by frankmilliron** [comment]
I'll try it in another machine. This one may have gremlins.

**Comment by frankmilliron** [comment]
OK. Tried on another ][+. Still hangs. Tried from first partition instead of second as well. Still hanging randomly on demos. machine passes diagnostics fine otherwise. *shrugs* I haven't tried this with a CFFA3000.

**Comment by peterferrie** [comment]
Can you reproduce it on the same demo each time?
i.e. type the name, press space to see the screenshots, right-arrow to
start the demo.
If there's one demo that always does it, it might help me to locate the problem.

**Comment by frankmilliron** [comment]
Apple Cider Spider and Conan both set it off. I can get it to halt in MAME using the 6502 CFFA driver.

mame64 apple2p -skip_gameinfo -window -sl7 cffa202 -hard1 Total Replay v2.0.2mg

start the cider spider demo and then hit return. MAME shows a 'hlt' at FC58. Maybe the language card isn't getting turned off and it's hitting an illegal opcode? On the real machines I don't need to hit a key.

**Comment by peterferrie** [comment]
MAME isn't a good repo here - it has a bug in the LC handing which I
have yet to fix, which is triggered by this game and others, but it
might be pointing me in the right direction in any case.

**Comment by peterferrie** [comment]
Fixed by 1a49667811e8d5dd903f1582dfc39237cd7b8187 and 
7e7f111dcc539ed963f77dfa686683868fc72198
