### ISSUE TITLE
TR's joystick calibration not working for AppleWin for bottom-left position

### ISSUE THREAD

**Issue by tomcw** [a2-4am/4cade#500]
Using "Total Replay v5.0-alpha.3" and also TR built from HEAD of master - [1256662](https://github.com/a2-4am/4cade/commit/12566629ead8d0ffe21461430e20f00602a38830)
When I move the joystick[1] to the bottom-left position, instead of reading (0,255), it reads (0,11), eg:

[1] "joystick" can be: cursor/numpad keys or mouse emulating a joystick.

![TR-Joystick-calibration](https://user-images.githubusercontent.com/6696896/192149078-e787ff33-4c52-4aa6-8ff6-b835df2c40e1.png)

NB. I tried with MAME 0.246, and this works fine - but it it has other problems: eg. Learning with Leepers (see below) and Boulderdash (when you move right or down, using the numpad as a joystick).

The issue is that AppleWin emulates analogue joysticks with maximum positions >255.
`PREAD` will still only return 255, but some games (eg. Learning with Leepers) expect joysticks to have a higher max position - they have custom routines to read both x and y simultaneously.

In TR the joystick read code has a `WAIT` routine (called from $4070) which isn't waiting long enough. Instead of calling with A=$20, change to A=$21 and it now works.

The specific reason is that the $C070 access isn't having an effect, as the timer hasn't expired yet (similar to the issue with Space Spikes, as discussed with @peterferrie in the "totalreplay" Slack channel).

Are you able to change the `LDA #$20` at $406E to `LDA #$21` ?

**Comment by xotmatrix** [comment]
I can confirm the same issue with a real joystick on a real Apple //e. I'm surprised this wasn't seen before.

**Comment by peterferrie** [comment]
Joystick calibration is lifted from MECC-A240 Computer Inspector v1.0.  People at the time probably just sighed and moved on.
I'll fix our version, and this is not an AppleWin issue after all.

**Comment by peterferrie** [comment]
fixed in d6e371dbd4088d531f68854559c941a1467dbfc6
