### ISSUE TITLE
Space Spikes has garbage on screen during gameplay

### ISSUE THREAD

**Issue by frankmilliron** [a2-4am/4cade#501]
Virtual II - Space Spikes seems to have graphic glitches when pressing button 1 during gameplay.
![Screen Shot 2022-09-27 at 9 18 04 AM](https://user-images.githubusercontent.com/34376619/192671338-98bbfe8a-5824-47e2-ae01-410ece9862c0.png)

**Comment by peterferrie** [comment]
Yes, that's how the original behaves, too.  Don't use button 1, only 0.

**Comment by xotmatrix** [comment]
This game has a lot of problems. Also locks up when idle or during a win/loss condition. Also still crashes after the second unpack following the title screen when the joystick is in certain positions.

**Comment by peterferrie** [comment]
I will check on these.

**Comment by xotmatrix** [comment]
It does some stack manipulation and gets stuck in a RTS loop at D834.

**Comment by xotmatrix** [comment]
This video shows the game running better, including what is supposed to happen when PB1 is pressed. 
https://www.youtube.com/watch?v=k6bcxPrYfj8

**Comment by peterferrie** [comment]
garbage is fixed in ad23f801b92396e9142f3feda9cb6827630c75f2, perhaps joystick too.
