### ISSUE TITLE
Galaxian demo crashes while loading

### ISSUE THREAD

**Issue by frankmilliron** [a2-4am/4cade#502]
Galaxian is crashing somewhere in "+LOAD_XSINGLE title". Looks like the load address may be getting set incorrectly to "$92" instead of "$72" ($0372) where "title" lives.

**Comment by peterferrie** [comment]
I forgot to update the _FileInformation when I moved the load address.
fixed in d051ffc3f664b1a1472e5971290b08f247b14dc8
