### ISSUE TITLE
Prince of Pursia doesnt launch when launched via GS/OS

### ISSUE THREAD

**Issue by erichelgeson** [a2-4am/4cade#507]
Using 5.0 beta 1

Launch GS/OS 6.0.4 on one 32mb image
Second image is TR 5.0b1
Double click on TR Launcher
Can play most games, but Prince of Pursia just goes to a black screen.

When booting directly off the TR 5.0b1 image (no GS/OS) PoP works fine.

Setup:
IIgs ROM1
Apple II SCSI Card (Sandwich II) -> BlueSCSI
ByteBoosters 8MB DarkRAM Apple IIgs Memory Expansion Card

Happy to grab any additional debug info with guidance.

**Comment by peterferrie** [comment]
Please share the GS/OS image.  It sounds like an "it works on my machine" issue because we have perhaps different configurations.

**Comment by erichelgeson** [comment]
Very well could be! I grabbed a prebuilt 6.0.4 image and I'm a pretty new to the IIgs - I zipped up the one I am using: https://drive.google.com/file/d/1CrV-kEnVTAI5R0G8umbyEOV9cKjDFQBe/view?usp=sharing

If you have another image I could try please let me know.

**Comment by erichelgeson** [comment]
Did a fresh install from LiveInstall.po and works.
