### ISSUE TITLE
ootw crashes at the end of levels

### ISSUE THREAD

**Issue by deater** [a2-4am/4cade#51]
"Out of This World" crashes on the end of levels when it's loading the next level from disk.

I've had this happen on Applewin 1.27.5.0 and Applewin 1.29 (running under Wine on Linux if that matters) both with II+ and IIe emulation.

Finishing Level 1, the game is halted stuck at address BF05
Finishing Level 4 it drops to the monitor at BF02
Level 2 crashes at the "My Tuba" scene to the monitor at A07F

**Comment by peterferrie** [comment]
Okay, completely my fault.  During testing, I didn't see $BFxx being
altered, but it does happen eventually.  At least the fix is easy.

**Comment by deater** [comment]
my fault too for sort of vaguely feeling like I did use $BF00 when you said that, but I couldn't remember off the top of my head what part of the code used it.

There's no reason OOTW has to use $bf00 (although Level 2 is a tight fit in 48k).  I don't know if there's some sort of best-practices guide for writing new code so it plays well with total replay.

**Comment by peterferrie** [comment]
It's fine.  I have room to swap the page around.  There's no style
guide.  Expect TR to be updated to support your environment, and not
the other way around.

**Comment by peterferrie** [comment]
Fixed in 0aba954dbdb38fe704c5a57d0c79c719971c11a9.
