### ISSUE TITLE
Vertical stripes on Flapple Bird when used with Apple IIe Card inside vintage Mac

### ISSUE THREAD

**Issue by JDW1** [a2-4am/4cade#518]
I recently released my Apple IIe Card Part II video where I mentioned Total Reply 5.0b2 and the fact I get vertical stripes in FlappyBird.  A member of the Apple II group on FaceBook replied that he does NOT get those vertical stripes when using Total Replay 5 on his real Apple II.  It probably is just some video quirk specific to the IIe Card, but since I am not sure about that I wanted to report the matter here.

Here's a side-by-side showing the stripes only on the IIe Card machine...

![image](https://user-images.githubusercontent.com/3928027/199140506-9b7c10e7-030b-4563-82be-529aec048ea6.png)

And here's the section of my video which shows more of that game in action:
https://youtu.be/ebftAlXGgbk?t=3146

**Comment by xotmatrix** [comment]
I'm not an expert but I think this is a problem with the Apple IIe card software and its handling of double-lores graphics mode. It is certainly not limited to Total Replay. Since the video is generated by the Mac software, maybe it could be fixed, but you appear to be running the last released developer version.

Another demonstration of the problem.
https://forums.atariage.com/topic/290174-opinions-on-the-apple-iie-emulator-for-the-macintosh-lc/#comment-4257439

**Comment by peterferrie** [comment]
I think the cause is that the IIe card uses a different palette compared to actual hardware for double-res graphics, and Flapple Bird does not support this case.  It's fixable in software, at least.

**Comment by xotmatrix** [comment]
I don't this it is just a palette issue. It looks like the bitstream coming from the AUX memory is delayed/shifted by one place (eg. AQUA 1110 -> LBLU 0111; LGRN 1100 -> MBLU 0110; YELO 1101 -> AQUA 1110). DHGR renders correctly, so something specific about DGR is not handled right. Hard to be sure what is going on though. In that video, when monochrome is enabled, the output seems extremely weird. 

One could potentially patch the game to output different/shifted bytes into AUX to compensate but is that something that should even be entertained?

**Comment by peterferrie** [comment]
Looking at the Bejeweled source code, which has its own workaround for the issue, the values for pixels in aux memory are made identical to the ones in main memory, instead of being shifted by 1.  A fix could be a copy-paste, but presumably all of the DHGR titles would need to be patched similarly, with varying degrees of difficulty.  Unfortunately, I can't agree to this.

**Comment by peterferrie** [comment]
It appears to be only one title in TR that's affected.  That's totally doable.

**Comment by JDW1** [comment]
> Another demonstration of the problem. https://forums.atariage.com/topic/290174-opinions-on-the-apple-iie-emulator-for-the-macintosh-lc/#comment-4257439

With the aim of investigating the "problem" you cited, I registered at that forum 24 hours ago so as to ask the person who generated those specific color bars about HOW they were created. Sadly, I have not been approved yet.  I then posted in the Apple II Enthusiasts group on FaceBook to ask BASIC experts how to generate those exact bars you linked in that forum post, but know one knows.  One kind person did give me the following code:

`10 GR:FOR I=0 TO 15: COLOR=I: FOR J=0 TO 1:VLIN 0,39 AT (I*2)+J:NEXT J,I`

That code produces these bars in the Virtual ][ emulator running on my modern Mac...

<img width="595" alt="image" src="https://user-images.githubusercontent.com/3928027/199433730-1923a8e3-4683-4915-85cd-e111698d2af9.png">

And the same code produces pretty much the same bars on my Color Classic Mystic (LC575) with IIe Card...

![image](https://user-images.githubusercontent.com/3928027/199434038-81c5be13-48b1-4bcf-97cc-f2fdd9aef2a1.png)

So if there is a problem as specified by the forum posts you linked for me, either that problem doesn't exist when the IIe Card is used on the LC575 motherboard, or I need to generate the exact same bars as are shown in that forum post (which remains a great mystery).

**Comment by xotmatrix** [comment]
Those color bars in that post were generated in DGR mode using some AppleSoft "ampersand" extensions. There are a few different ones but it looks like they used Beagle Graphics.

http://beagle.applearchives.com/the_software/vintage_beagle_bros_softwar/beagle_graphics.html

I've made this disk which will load the extension and draw the color bars.

[dgr-colorbars.zip](https://github.com/a2-4am/4cade/files/9919788/dgr-colorbars.zip)

**Comment by JDW1** [comment]
> I've made this disk image which will load the extension and draw the color bars when you boot it.
> [dgr-colorbars.zip](https://github.com/a2-4am/4cade/files/9919788/dgr-colorbars.zip)

Wonderful, thank you!

Using your *.do in Virtual ][ running as a IIe, I get these bars...

<img width="1100" alt="image" src="https://user-images.githubusercontent.com/3928027/199501115-1c67ed01-8da8-4aed-973f-f6329e47a6c5.png">

On my Color Classic Mystic with IIe Card, I unfortunately get this...

<img width="1100" alt="image" src="https://user-images.githubusercontent.com/3928027/199501154-46a26572-0faf-4232-8503-44e03e60d5dc.png">

So I guess [that forum thread](https://forums.atariage.com/topic/290174-opinions-on-the-apple-iie-emulator-for-the-macintosh-lc/#comment-4257439) is right after all.  Hmmm...

**Comment by peterferrie** [comment]
fixed! in d1a8455dacc9c86334a639bae0d032eb073e0f31
