### ISSUE TITLE
Titles unavailable in search

### ISSUE THREAD

**Issue by lazaj** [a2-4am/4cade#521]
Hello,

I'm currently testing version 5 beta 3 on my IIc with ROM4x and FloppyEmu.
Some titles doesn't show in search mode.
Arkanoid is an example, I press A then R then K ... but no Arkanoid, just Ardy the Aardvark.
Link to picture : [Link to picture ](https://www.instagram.com/p/Ck8e21tIWYL/?utm_source=ig_web_copy_link)
I've tried the same with Virtual][ without problem

**Comment by frankmilliron** [comment]
Arkanoid requires a joystick. Do you have one connected? Total Replay will filter out any games that require joystick if one is not detected.

**Comment by lazaj** [comment]
Thanks, I don't have a joystick connected (and no available joystick for Apple II).

**Comment by frankmilliron** [comment]
No dice then. You can either find a real one, or use the following to build one with modern parts.
https://blondihacks.com/apple-ii-gamepad-prototype/
