### ISSUE TITLE
Transition effect is hitting IRQ vector

### ISSUE THREAD

**Issue by frankmilliron** [a2-4am/4cade#523]
One of the transition effects is changing the value of $3FF / IRQ vector. If you watch that memory location, it will eventually change from #$01 and then switch between #$FC and #$F8 until the effect is finished and 'Reenter' changes it back to the correct value of #$01. Possibly an off-by-one or something? Changing this location will cause instability in certain setups of the super serial card and other hardware.

I am actively looking for other IRQ fixes in the demos since I think a few may have regressed with the full conversion to prelaunch style launchers. I have a few compatibility fixes forthcoming, but ran into this transition issue while testing.

**Comment by txgx42** [comment]
I tracked down this much:

**Comment by txgx42** [comment]
I tracked down this much, there are a few FX that use two macros back to back: BUILD_MIRROR_COLS, followed by BUILD_HGR_LOOKUP_TABLES_X_IS_ALREADY_0. 

BUILD_MIRROR_COLS finishes with X=FF, but BUILD_HGR_LOOKUP_TABLES_X_IS_ALREADY_0 assumes X = 0

**Comment by frankmilliron** [comment]
If I change the "BUILD_HGR_LOOKUP_TABLES_X_IS_ALREADY_0" macro to include ldx #0 and the beginning, it doesn't seem to hit it anymore. Guessing that's not the correct fix, but X coming into the macro not being zero seems to be the problem.

**Comment by peterferrie** [comment]
There's a BUILD_HGR_LOOKUP_TABLES macro that zeroes X.  I will change to use this and see how it goes.

**Comment by frankmilliron** [comment]
The fix works. Does not hit $3FF anymore. There was a typo which I fixed in my last PR as it wasn't building.
