### ISSUE TITLE
Cannonball Blitz freezes at level 3.

### ISSUE THREAD

**Issue by nobuddyuno** [a2-4am/4cade#527]
Using [Download Total Replay](https://archive.org/download/TotalReplay/Total%20Replay%20v5.0-beta.3.hdv) (version 5.0-beta.3, released 2022-11-09, 32 MB disk image
Using https://github.com/AppleWin/AppleWin/releases/tag/v1.30.12.0 default out of box settings enhanced //e.
Same AppleWin settings, woz-a-day version does not freeze at level 3.

**Comment by peterferrie** [comment]
fixed in 5c543b8e487a65fee8283f8989045b5e97216f19
