### ISSUE TITLE
Fix PoP keyboard control

### ISSUE THREAD

**Issue by roughana** [a2-4am/4cade#541]
The issue is identified & documented here with video evidence
https://www.applefritter.com/comment/101047#comment-101047
TR's PoP exhibits the problem on my Platinum //e.

I believe the OP is referring to published PoP source code.
Search for the KEYS routine which includes the following: 
LDA $C000
STA keypress 
LDA $C010
STA keydown
JSR KREAD

Unfortunately, a full solution is not available at the link, only a description of the problem and a suggested solution:

"The ideal fix would replace [LDA $C010, STA keydown] with a test of the previously-saved AnyKeyDown state, and a branch to skip the LDA $C010 in the case when the previous AnyKeyDown indicated all keys had been released, plus a test LDA $C000 to resume normal activity after the next KEYSTROBE."

**Comment by peterferrie** [comment]
fixed in dbd77dc70533452206cf80761ef0d67c17b1a7a5
