### ISSUE TITLE
The Easy Access init in GS/OS causes the keyboard to not work in games

### ISSUE THREAD

**Issue by rmcardle** [a2-4am/4cade#542]
When the Easy Access init is installed in GS/OS, the keyboard doesn't work in games. Even Ctrl-Reset and Apple-Ctrl-Reset don't work. Removing EasyAccess from System:System.Setup and rebooting fixes the problem.

Tested with System 6.0.4 on a real ROM 01 IIgs and under GSPlus with ROM 03.

**Comment by peterferrie** [comment]
This is a problem with Easy Access.  We can't fix this.

**Comment by rmcardle** [comment]
If this isn't something that can be fixed, could you put something in the README or somewhere so other people know about the incompatibility and how to fix it? It wasn't easy to figure out what was causing this.
