### ISSUE TITLE
Nightmare Gallery demo crashes with stack overrun

### ISSUE THREAD

**Issue by frankmilliron** [a2-4am/4cade#543]
Start Nightmare Gallery. Let demo run through 20-30 times. Eventually it will crash due to a stack overrun. Virtual II and MAME both show it. The original "Nightmare Gallery.woz" file does not exhibit the behavior.

**Comment by peterferrie** [comment]
The game has a stack leak, and we have the timer code on the stack for the compatibility fix.  I'll move it.

**Comment by peterferrie** [comment]
fixed in 01f51765442d53fd1641663bc8f0635acb37a7f7

**Comment by frankmilliron** [comment]
Oops my bad!!
