### ISSUE TITLE
4cade compilation error

### ISSUE THREAD

**Issue by QUIZASERAQ** [a2-4am/4cade#544]
Hello From Germany,
I tried compiling the latest code on win10 today..

Unfo it does not find 'asmprelaunch' .. and gives me two indexing errors..  
with runtime errors in MS JScript 'buildpre.js(11, 1)' and 'addfile.js(4, 1)'

.hdv has been generated but wont continue to boot in AppleWIn right after TOTAL REPLAY logo.

Is this an error on my side or can you help fixing it? Thanks

Q.

**Comment by peterferrie** [comment]
try "winmake clean" first, every time now.

**Comment by QUIZASERAQ** [comment]
already did.. and made sure the build folder is wiped.. 
but it does not solve the problem..

**Comment by philtimmes** [comment]
You must go into Windows Defender settings, and set Windows Defender to ignore the 4cade folder

**Comment by peterferrie** [comment]
what was the last "indexing" string that it showed before the error?

**Comment by QUIZASERAQ** [comment]
WIndows Defender was already off.. but I added an exclusion for that folder to be sure.. didn't help..

**Comment by QUIZASERAQ** [comment]
![image](https://user-images.githubusercontent.com/3315077/232244999-71ce4f86-f661-42fa-9a72-09fc5f1f1e9c.jpeg)

**Comment by QUIZASERAQ** [comment]
Am off Keyboard now, thx for investigation.. but no pressures.. can also wait for next binary release..

**Comment by peterferrie** [comment]
I would like to solve this rather than you waiting.  When you return, does a "build/PRELAUNCH.INDEXED" directory exist?

**Comment by philtimmes** [comment]
Try typing `chcp 437` on the command line before running winmake dsk.

**Comment by QUIZASERAQ** [comment]
Jep, does exist but is empty..

> I would like to solve this rather than you waiting.  When you return, does a "build/PRELAUNCH.INDEXED" directory exist?

**Comment by QUIZASERAQ** [comment]
> Try typing `chcp 437` on the command line before running winmake dsk.

![image](https://user-images.githubusercontent.com/3315077/232278987-f614e596-b67c-4838-8248-135bf4710245.jpeg)

Does not help..
PRELAUNCH.INDEXED empty again

**Comment by peterferrie** [comment]
I overlooked the first error.  asmprelaunch target is not found.  Please attach your winmake.bat.  Maybe a bad download?  Perhaps the answer will become clear.

**Comment by QUIZASERAQ** [comment]
Well.. i just dlded the package two days ago and did not alter anything..
[winmake.zip](https://github.com/a2-4am/4cade/files/11252926/winmake.zip)

**Comment by QUIZASERAQ** [comment]
well.. did so.. that debug.txt shows less then console did..
[debug.txt](https://github.com/a2-4am/4cade/files/11253155/debug.txt)

does the path play a role.. i did compile it in c:/4cade/4cade-main

**Comment by QUIZASERAQ** [comment]
That cdmd output s like before.. do i need to update JScript or anything.. sorry the noob questions.. am no coder nor Win proof

Das Sprungziel - asmprelaunch wurde nicht gefunden.
C:\4cade\4cade-main\bin\buildpre.js(11, 1) Laufzeitfehler in Microsoft JScript: Die Datei wurde nicht gefunden.
C:\4cade\4cade-main\bin\addfile.js(4, 1) Laufzeitfehler in Microsoft JScript: Die Datei wurde nicht gefunden.

**Comment by peterferrie** [comment]
I don't think that you need to update anything, but the debug.txt should contain more text than that.  Please delete the "@echo off" line entirely, save the winmake.bat, and then run "winmake.bat > debug.txt".  The debug.txt should contain lines like "rem 4cade Makefile for Windows" if it worked.

**Comment by peterferrie** [comment]
I don't think the path is the problem, but I will try building it that way to be sure.

**Comment by QUIZASERAQ** [comment]
wow.. that took def longer to compile.. at least u got st to read now ;-)
[debug.txt](https://github.com/a2-4am/4cade/files/11253690/debug.txt)

**Comment by peterferrie** [comment]
does this print "1", "2", "3"?
[winmake.zip](https://github.com/a2-4am/4cade/files/11254195/winmake.zip)

**Comment by QUIZASERAQ** [comment]
echoes:
"1"
"2"
building prelaunch..."3"

**Comment by QUIZASERAQ** [comment]
Puts this into build folder:![image](https://user-images.githubusercontent.com/3315077/232582965-018549cf-6738-4c7e-8c4c-c59505c8a0a4.jpeg)

**Comment by QUIZASERAQ** [comment]
afk for today.. have a good one..

**Comment by peterferrie** [comment]
when you return, does this also print "1", "2", "3" when you "winmake dsk"?
[winmake.zip](https://github.com/a2-4am/4cade/files/11254863/winmake.zip)

**Comment by QUIZASERAQ** [comment]
that one went through all steps:

C:\4cade\4cade-main>winmake dsk
building fx...done
"1"
"2"
building prelaunch...done
"3"
building demos...done
converting gamehelp...done
indexing prelaunch...done
indexing titles...done
indexing gamehelp...done
indexing slideshows...done
indexing fx...done
indexing (d)hgr action...done
indexing (d)gr action...done
indexing shr...done
indexing demos...done
indexing single-loaders...done
indexing search...done
preparing index file...done

C:\4cade\4cade-main>


.. but the built .hdv says UNABLE TO LOAD PRODOS in AppleWIn

**Comment by peterferrie** [comment]
> .. but the built .hdv says UNABLE TO LOAD PRODOS in AppleWIn

I expected that.  To make your testing faster, I disabled the final step.
However, I think that means my other fix worked.  Please download the
latest version and retest.

**Comment by peterferrie** [comment]
Ah, now I know the cause.  It's a line-ending issue on Windows.
Until I can solve this automatically, you can open the winmake.bat in
Microsoft Word, Save As plain text, select "Windows encoding".  Then
it will work as it's supposed to.

**Comment by QUIZASERAQ** [comment]
Well.. it compiles fine now.. but.. sorry to tell u.. the.hdv loading still seems to be broken.. hangs on home screen.. seems to continuously read from HD but does only show TR logo.. tried on both AppleWin for WIndows and MicroM8 for OSX..
![Screen Shot 2023-04-18 um 09 48 58](https://user-images.githubusercontent.com/3315077/232709594-d27eb8d1-0b2f-4941-a8c6-ffa2eca07c43.jpg)

**Comment by peterferrie** [comment]
That's some progress, at least.  Please attach the .hdv, so that I can
compare with a working version.

**Comment by QUIZASERAQ** [comment]
[4cade.zip](https://github.com/a2-4am/4cade/files/11264589/4cade.zip)

**Comment by QUIZASERAQ** [comment]
sry.. that goto was not there.. anyhow I dlded again whole package.. but result still crappy..
[4cade.zip](https://github.com/a2-4am/4cade/files/11264765/4cade.zip)

**Comment by peterferrie** [comment]
you have Cadius in your path?  That's needed for the final step.

**Comment by philtimmes** [comment]
Make sure it's the cadius in the readme.md... the first one that comes up
in Google searches does not work.

**Comment by QUIZASERAQ** [comment]
afk right now.. will check tomorrow..

**Comment by peterferrie** [comment]
we require https://github.com/mach-kernel/cadius
because we're using a switch that the other one doesn't support, and will refuse to run.
That might explain why there are no files in the image.

**Comment by QUIZASERAQ** [comment]
Is there a precompiled Win version of the mach-kernel cadius avail somewhere? Thanks

**Comment by peterferrie** [comment]
yes, I will update this.  The first link points to the correct version, but the second one (that you show) does not.
prebuilt version: http://pferrie.epizy.com/misc/tmp/cadius.zip

**Comment by peterferrie** [comment]
> Yiiihaaaa... we made it! Using correct cadius did the trick.. have the 484
> games version running without probs! THANK YOU!

Yay!

> btw.. i accidentially hit ? outside the front page and found that game
> control hints pages. That new? Did never realize they exist. always thought
> ? works on front page only.. you def should indicate that function
> somewhere...

The title screen says "press ? for help".  We didn't want to add it to
all of the other pages.
It's been there for a long time.  Many games are missing their help
files, and we'd love help to fill in the gaps. :-)

> btw#2.. there do exist some JoyStick/ButtonFix versions.. at least I know
> for BANDITS (button 1 for fire) and APPLE PANIC and GORGON (JoyControl)..
> can provide them if needed...

Please send them.

> Great project that brings back nostalgic feeling every time I power up mi
> Pi4... keep on rolling and let me know in case u need a tester or supporter
> anyhow.

Thanks.

**Comment by QUIZASERAQ** [comment]
> btw#2.. there do exist some JoyStick/ButtonFix versions.. at least I know for BANDITS (button 1 for fire) and APPLE PANIC and GORGON (JoyControl).. can provide them if needed...
> Please send them.

Attached the altered games:
- Apple Panic and Gorgon now playable with Joystick
- Lode Runner with buttons switched for more intuitive hole digging
- Bandit with Shield set to Button 1 (instead of space)

Plus some other games I like that you may consider adding to the collection(s)!?

hth

Q.
[4CADE SUPPORT.zip](https://github.com/a2-4am/4cade/files/11320201/4CADE.SUPPORT.zip)

**Comment by peterferrie** [comment]
>> The title screen says "press ? for help". We didn't want to add it to all
>> of the other pages. It's been there for a long time. Many games are
>> missing their help files, and we'd love help to fill in the gaps. :-)

I understand now.  I will see if I can fit one more line.  We don't
control the vertical spacing, so it's going to be tight.

**Comment by a2-4am** [comment]
Eliminator is already in as Exterminator.

Night Flight is already in as Battle Cruiser.

Triple Arcade Insanity is a set of Arcade Machine games, which we will not include.

Word Munchers is an educational game, which we generally do not include. Likewise Robot Odyssey.

Cytron Masters could only be included if we could forward-port it to work on all supported Apple II models (incl. IIgs), and even then I'm not sure it's a good fit.

**Comment by a2-4am** [comment]
We already have the Applesoft version of Woz's Breakout.

**Comment by QUIZASERAQ** [comment]
> - Bandit with Shield set to Button 1 (instead of space)
> I will check on this. Shield is 'S', space is for shooting, in our version.

After CTRL-P when bandits arrive - the one I sent is Btn0 for fire and Btn1 for shield....  just played it few mins ago ;-)
