### ISSUE TITLE
Treasure Dive acts like it has a lores screenshot

### ISSUE THREAD

**Issue by xotmatrix** [a2-4am/4cade#545]
Treasure Dive acts like it has a GR or DGR screenshot but it does not. I was unable to work out where the problem is.

![Mono6502_2023-04-30_04-10-34](https://user-images.githubusercontent.com/14209329/235342828-eb4bdc12-f5d6-46f5-b806-1e0384428f5f.png)

![Mono6502_2023-04-30_04-11-15](https://user-images.githubusercontent.com/14209329/235342831-e6898089-0173-4a7b-8908-8a1de1c0951a.png)

**Comment by peterferrie** [comment]
It's because it has no graphical title screen, so we have only screenshots of the game itself.
