### ISSUE TITLE
Support for 4play configuration

### ISSUE THREAD

**Issue by roughana** [a2-4am/4cade#55]
4Play is a recent interface for digital joysticks. http://lukazisloot.blogspot.com/
It requires some software changes to be able to support it. The changes have been made for several games that Total Replay supports.
http://lukazi.blogspot.com/2017/08/apple-ii-4play-joystick-card-software.html

This is an enhancement request to determine that the 4play is installed and to provide 4play compatible versions of titles that Total Replay supports.

**Comment by peterferrie** [comment]
Converted titles have replaced keyboard and/or joystick controls with 4play support.  Those games might become unplayable as a result without a 4play device.
