### ISSUE TITLE
Human readable games list

### ISSUE THREAD

**Issue by JPT77** [a2-4am/4cade#550]
Hi, 

I am currently working on making the Apple IIe in our local museum more fun to play. 
For this I wanted to try all available games and document them. 
Now I found res/GAMES.CONF which is a good starting point. 

What about creating a more human readable list and sync both lists in whatever direction?

Currently I got the following columns: 
Name
Model - Apple II, IIe, IIgs etc
Media - where to find, eg Total Replay
Year	
Distributor		
Quality - How much fun to play?
Type of game - Adventure, arcade etc
Color - if it's color
Input - input options like joystick, mouse, keyboard and which keys if not documented

Since the total replay list got 460 games, this job is hard for a single person... I worked a day and finished like 30 games.

**Comment by a2-4am** [comment]
This is a good idea but out of scope for this project.

**Comment by roughana** [comment]
This idea has a lot of overlap with the #Everything project.
You may like to join the A2 Infinitum slack space and the #Everything channel. Particularly the pinned posts and the main spreadsheet http://a2.click/everything
