### ISSUE TITLE
Maybe 4adventure 4rpg ;-)

### ISSUE THREAD

**Issue by BackSpace54** [a2-4am/4cade#555]
Hi,
thanks for those awesome packs, have you planned to create others packs like 4adventure (Amazon, Dark Crystal, Haunted house, Mask of the Sun, Masquerade, S.A.G.A serie, Sherwood Forest, Time Zone, Transylvania, and so on...) and 4rpg (Bard's Tales serie, Deathlord, Might and Magic serie, Phantasie serie, Questron serie, Ultima serie, Wasteland, and so on...).
Best regards.

**Comment by a2-4am** [comment]
Yes, we have concrete plans for a graphic adventure pack in the future.
