### ISSUE TITLE
Feature Request for Alternative Implementation of GAME SEARCH in Total Reply

### ISSUE THREAD

**Issue by JDW1** [a2-4am/4cade#558]
The origin of this Feature Request began here:
https://github.com/a2-4am/4cade/issues/557

Polling the Apple II community on FaceBook shows that the majority of Total Reply users who responded to the poll define game-search as being either Hit or Miss or Mostly a Miss. Only a minority said they get to their desired game every time.  This behooves us to ponder an improved means of search.

In a comment under my FaceBook poll, Mitchell Spector suggests this:
_Best solution? Have an option for a POP-UP scrolling list of all games available (or even switch to an all text screen if necessary--allow us to select from an alphabeticalized listing)._

I myself am thinking of something a little different, yet still somewhat similar to what is done now. For example, I propose you present the user with a new screen immediately upon detecting a key-press.  On that new screen, show the key they typed, and continue to show any additional keys typed.  Only begin search AFTER they hit Return.  So long as the characters they type match a game's name, that should result in a perfect match every time.

If there could be a "text field overlay" atop whatever screen is currently displayed, that too would work, so long as it shows the user they characters they are typing, and so long as search does not begin until they type return.  The reason to delay search until Return is pressed is to better ensure no typed characters are missed, which might happen if search commences WHILE characters are still being typed.

With that said, the exact method of improving search isn't so important so long as it mostly eliminates the hit or miss kind of searching that many people are experiencing now.

Lastly, this Feature Request should not be viewed in a negative light.  It is not a complaint.  Total Replay developers have done amazing work on Total Replay.  It is truly fantastic, and shows how many hours of toil the creators have put into it.  The aim of this Feature Request is merely intended to spark a discussion on to improve on an already great piece of software.  Remember that good methods of SEARCH are all around us.  Search is what led to Google becoming the behemoth it is today.  The better any given search feature is for the end user, the happier and more productive that user can be.

**Comment by wyatt-wong** [comment]
I thought the screenshot that James Wages describe looks like the macOS Spotlight search. When user activate the spotlight search with the shortcut key of Command+Space Bar, a spotlight search pop-up in the middle of the screen and accept user input. Upon each keypress, the search narrow down and filter those objects that match with the text: and similar when the text were erased by backspace key, the search widen and filter those objects that match with the text.A full screen that pops up to show all the games for user to select it with up and down arrow keys is a bit overkill and consumes more storage spaces in the limited size of HDV file which I don’t recommend at all.Sent from my iPhone 12 Pro MaxOn Jan 5, 2024, at 22:38, James Wages ***@***.***> wrote:﻿
The origin of this Feature Request beganhere:
#557
Polling the Apple II community on FaceBook shows that the majority of Total Reply users who responded to the poll define game-search as being either Hit or Miss or Mostly a Miss. Only a minority said they get to their desired game every time.  This behooves us to ponder an improved means of search.
In a comment under my FaceBook poll, Mitchell Spector suggests this:
Best solution? Have an option for a POP-UP scrolling list of all games available (or even switch to an all text screen if necessary--allow us to select from an alphabeticalized listing).
I myself am thinking of something a little different, yet still somewhat similar to what is done now. For example, I propose you present the user with a new screen immediately upon detecting a key-press.  On that new screen, show the key they typed, and continue to show any additional keys typed.  Only begin search AFTER they hit Return.  So long as the characters they type match a game's name, that should result in a perfect match every time.
If there could be a "text field overlay" atop whatever screen is currently displayed, that too would work, so long as it shows the user they characters they are typing, and so long as search does not begin until they type return.  The reason to delay search until Return is pressed is to better ensure no typed characters are missed, which might happen if search commences WHILE characters are still being typed.
With that said, the exact method of improving search isn't so important so long as it mostly eliminates the hit or miss kind of searching that many people are experiencing now.
Lastly, this Feature Request should not be viewed in a negative light.  It is not a complaint.  Total Replay developers have done amazing work on Total Replay.  It is truly fantastic, and shows how many hours of toil the creators have put into it.  The aim of this Feature Request is merely intended to spark a discussion on to improve on an already great piece of software.  Remember that good methods of SEARCH are all around us.  Search is what led to Google becoming the behemoth it is today.  The better any given search feature is for the end user, the happier and more productive that user can be.

**Comment by ricardocontieri** [comment]
If it suits to this thread, it would be great if we could browse games by hardware capbility (ie. only mockingboard compatible games, only IIe required) based on what is already know. Further down the road, if we could search by DHGR, HGR etc it would also be a great feature. Thanks!

**Comment by JDW1** [comment]
> If it suits to this thread, it would be great if we could browse games by hardware capbility (ie. only mockingboard compatible games...

I made a list of Mockingboard compatible games that are found on Total Reply....

* Berza!
* Bruce Lee
* G.I. Joe
* OidZone
* Pitfall II
* SkyFox
* The Spy Strikes Back
* Thunder Bombs
* WillyByte
* Zaxxon

These are more Mockingboard compatible games NOT on Total Reply...

* Airplane Simulator (Airsim-3): http://tinyurl.com/28zee8ky
* Angry Birds (may not be free): https://8bitshack.org/post/angrybirds/
* Attack of the Petscii Robots (“a2robots” — not free!): http://tinyurl.com/cxuh98ku
* Black Belt
* Nox Archaist (not free!) https://6502workshop.com/
* Popeye
* Ultima III, IV & V

**Comment by HelixNRG** [comment]
Note that Black Belt v2 is on the Instant Replay collection.

**Comment by roughana** [comment]
There are other places with comprehensive lists of Mockingboard titles. There is no need to try to capture that here
http://www.applevault.com/hardware/sweet_micro_systems/mockingboard/

**Comment by JDW1** [comment]
> There are other places with comprehensive lists of Mockingboard titles. There is no need to try to capture that here http://www.applevault.com/hardware/sweet_micro_systems/mockingboard/

I disagree profoundly, and here's why.  I already knew about the link you provided when I submitted my earlier post on Jan.7.  Anyone who reviews my list will see that I listed many items not found at that linked web page, although there is a little overlap. But what I listed are titles I tested and verified myself, so I am 100% confident in them.

If anyone wishes to add the titles in my list to that linked web page, by all means, please do so.  But lets no fool ourselves into thinking that other web page is "comprehensive" and 100% complete, because as my list shows, it is not.  I suspect there are likely more titles out there too.  I simply don't know about them.

**Comment by roughana** [comment]
Let's agree 
1) that the list will forever continue to grow as more games are released that support it.
2) that trying to capture that list here is out of scope
I would encourage you to provide your updates to Kevin to help his list be better.

**Comment by JDW1** [comment]
Friend, while I greatly appreciate your attempt to get along, I once again cannot agree completely with you on your suggestion, and here's why.  People do not live forever.  So when you have just one guy maintaining a website, like Paul Pratt did with Mini vMac, then everything comes to a screeching halt when that person passes away (which seems to be what occurred with Paul), UNLESS somebody else takes over (which isn't always possible), or rebuilds the web page that the deceased had made and then posts it to their own server and then maintains it until their death.  But I would say that a community based approach would be best, as people could then take over the original work with ease.

I personally do not know who Kevin Greene is, other than the person whose name appears on the page you linked for us.  But I have no means to contact him because clicking on his name, which you'd think would open contact info, yields a page which says NOT FOUND.  As such, if you are able to contact Kevin, my advice would be to just send him a link to our discussion here, and he can then add my list to his.  That would be the best solution for now, until a community-editable wiki of sorts is uploaded for all to read, update and enjoy many decades into the future.

Thank you.

**Comment by roughana** [comment]
I have forwarded a link to your message to Kevin.

**Comment by roughana** [comment]
You included in your list of Mockingboard compatible titles in Total Replay: Bruce Lee, GI Joe
I was not aware these support Mockingboard. There is no prelaunch patching for these titles so a) either the games do their own slot scan that works, or b) you tested in slot 4.
I need to check they work with MB in other slots.

**Comment by JDW1** [comment]
Music and Sound Effects.  
You can test this yourself even in an emulator. Launch your copy of Virtual ][ and use something like the IIc emulation, then download a G.I. Joe disk, and give it a test.  Mockingboard is enabled in Virtual ][.

**Comment by roughana** [comment]
I have tried Total Replay's versions of GI Joe and Bruce Lee in AppleWin which emulates Mockingboards. I tried them both with Mockingboards active and not active.
The title music in GI Joe is played the same without Mockingboards being activated.
The text screen title music in Bruce Lee is played the same without Mockingboards being activated. Bruce Lee even acknowledges Electric Duet as the resource used to create the music.
My conclusion is that they both do not have Mockingboard music or sound effects. I would be pleasantly surprised to be re-educated otherwise. Perhaps you tried other disk image versions than those that are present in Total Replay?

**Comment by JDW1** [comment]
You are correct.  I confirmed it on my IIc (Mockingboard removed) and in Virtual ][ using the IIe emulator with and without the Mockingboard installed virtually.  Sorry for the mistake.

Here's my updated List:

Mockingboard Enabled GAMES
* 8bit-Slicks††
* Airplane Simulator (Airsim-3): http://tinyurl.com/28zee8ky
* Alien Clonepure: https://archive.org/download/alienclonepure
* Angry Birds†
* Ape Escape† (requires SC-01 speech chip)
* Attack of the Petscii Robots (“a2robots” — not free!): http://tinyurl.com/cxuh98ku
* Berzap!†
* Black Belt††
* Jumpy Guy: https://tinyurl.com/y5ctnf75
* Lady Tut†
* Lancaster†
* Maze Craze: https://tinyurl.com/5ca3pm95
* Microbe: https://tinyurl.com/4tv6hd3f
* Night Flight: https://tinyurl.com/252fy68b
* Nox Archaist (not free!) https://6502workshop.com/
* Oubliette 2021 (IIc incompatible?): https://8bitshack.org/post/oubliette2021/
* OidZone†
* Pitfall II†
* Popeye: https://tinyurl.com/29e3hn22
* Pyramid of Ra: https://tinyurl.com/3hv5p7na
* Silent Service††
* SkyFox†
* TAC: Tactical Armor Command: https://tinyurl.com/3cwfad82
* The Spy Strikes Back†
* Thunder Bombs†
* Ultima III, IV & V: https://tinyurl.com/5xr6nper
* WillyByte†
* Zaxxon†

† Total Reply games
†† Total Reply II games

**Comment by roughana** [comment]
You have omitted Apple Cider Spider, Battle Cruiser, Bouncing Kamungas, Crime Wave, Genius 1/2/3, Lethal Labyrinth, from your list of MB supporting titles that are in TR.
[Feel free to edit your above comment(s) rather than creating a new one]

**Comment by JDW1** [comment]
While I certainly will revisit some of those to reconfirm, I can tell you right now that I deliberately left out Apple Cider Spider and Bouncing Kamungas because I couldn’t hear Mockingboard sound anywhere in those games, so if you can, please tell me specifically where I’m supposed to hear it and I will check again in a more detailed way. Thank you.

**Comment by roughana** [comment]
The sound effects in Apple Cider Spider use the MB if it is available. The short intro tune as you start to play is also MB. If you dont have MB installed, then regular 1-bit sound effects are used. So MB doesn't really add much. But it is supported.

**Comment by roughana** [comment]
The Bouncing Kamungas has speech support and uses MB for sound effects e.g when spiking a Kamunga, lightning, bouncing.

**Comment by a2-4am** [comment]
This is not an appropriate forum for this discussion. Please take it elsewhere.
