### ISSUE TITLE
Seprentine hangs

### ISSUE THREAD

**Issue by audetto** [a2-4am/4cade#559]
Using 5.0.1 with AppleWin.

![image](https://github.com/a2-4am/4cade/assets/212523/254b6235-86cf-4333-9d99-58bc44456456)

in the debugger

![image](https://github.com/a2-4am/4cade/assets/212523/f939b78d-b752-4b01-9414-22d2274b91d7)

no matter what I key I type, it goes nowhere.

**Comment by peterferrie** [comment]
fixed in 30151dd22d4c599981fb3a715e6a3c4e79f15196
