### ISSUE TITLE
Total Replay hangs at boot immediately after displaying "128K" message

### ISSUE THREAD

**Issue by rantler** [a2-4am/4cade#560]
I don't have a joystick installed at the moment. Could this issue be caused by that? I've tried several different versions of Total Replay disk images and I'm using a FloppyEMU and BMOW controller card. Other disk images appear to be working okay, both HD and floppy.

Maybe something wrong with my Apple IIe itself?

**Comment by peterferrie** [comment]
If you're comfortable with CiderPress or Cadius, I will make a you replacement Launcher program with debug messages and attach here.  That would help us identify the location of the hang.  If you'd prefer a full hdv then I'll find somewhere to put it.

**Comment by peterferrie** [comment]
might be fixed by 1f81a4f1306a17f268d36bbbfa242adabd153714

**Comment by rantler** [comment]
Thanks so much for the help and suggestion!

I cloned the repo and built from source without any issues. Unfortunately I'm still encountering the hang at startup. I've attached a couple of photos for reference.

I've got the Floppy EMU in slot #5 if that makes any difference and I'm using the BMoW Yellowstone controller card.

I also wanted to mention that I've tried this on a friend's Apple //e as well with several different versions of Total Replay and he's having the same troubles. He's also using the same BMoW hardware in his setup.

![image](https://github.com/a2-4am/4cade/assets/73775/6b1b58f8-d0b7-4145-9b09-f55ea74839c4)
![image](https://github.com/a2-4am/4cade/assets/73775/f2d6ecaa-2918-4ec8-a3dd-142c291f3155)

**Comment by wyatt-wong** [comment]
I build Total Replay from the source and did not have any problem. I am running it in Virtual ][ emulator.

Best Regards,
Wyatt Wong 

    On Monday, February 12, 2024 at 01:57:40 AM GMT+8, Randy Antler ***@***.***> wrote:  
 
 


Thanks so much for the help and suggestion!

I cloned the repo and built from source without any issues. Unfortunately I'm still encountering the hang at startup. I've attached a couple of photos for reference.

I've got the Floppy EMU in slot #5 if that makes any difference and I'm using the BMoW Yellowstone controller card.

I also wanted to mention that I've tried this on a friend's Apple //e as well with several different versions of Total Replay and he's having the same troubles. He's also using the same BMoW hardware in his setup.

image.png (view on web)
image.png (view on web)

**Comment by rantler** [comment]
I ended up getting a wDrive to see if that behaved differently and it turns out TotalReplay works perfectly on that device. This suggests that the problem lies with the Floppy EMU. I've tried several different versions of the firmware for Floppy EMU and they all hang in the same manner, so I'll reach out to BMOW for help.

**Comment by peterferrie** [comment]
okay, thanks for letting us know.  If Steve can reproduce the effect then I'm happy to work with him on a solution if software can fix it.

**Comment by rantler** [comment]
Steve kindly pointed me to [this article](https://www.bigmessowires.com/2022/10/23/nmos-6502-phantom-reads-odd-yellowstone-bugs/) which was a fascinating read. After downloading the [new firmware](https://www.bigmessowires.com/yellowstone/#downloads) and installing it, I'm pleased to share that the Floppy Emu, Yellowstone controller and Total Replay are playing nicely together. Great success!

**Comment by peterferrie** [comment]
Ah yes, we had a fine time investigating that one.  I had forgotten about
it.
I'm glad that it's working for you.
