### ISSUE TITLE
Super Zaxxon reset handling on IIgs

### ISSUE THREAD

**Issue by a2-4am** [a2-4am/4cade#565]
sitting on title screen, Ctrl-Reset hangs on IIgs

works on IIe

**Comment by a2-4am** [comment]
works in KEGS(Mac) recent build so might be a MAME bug

**Comment by peterferrie** [comment]
Race condition if reset is pressed during main unpacking, which happens
after title is shown but before the vector is changed to reboot.  I will
fix this.

**Comment by peterferrie** [comment]
ah no, that was Zaxxon's issue.  Super Zaxxon's thing is a MAME bug that's not banking in ROM again on reset.
