### ISSUE TITLE
Bejeweled needs reset vector

### ISSUE THREAD

**Issue by a2-4am** [a2-4am/4cade#573]
TR reset code is still present at bottom of stack but 3f2 points to 80C instead

tested on title page and during gameplay

**Comment by peterferrie** [comment]
reset quits via ProDOS

**Comment by a2-4am** [comment]
doesn't work in Virtual II
<img width="1288" alt="Screenshot 2024-05-11 at 7 05 47 PM" src="https://github.com/a2-4am/4cade/assets/22437310/0ba20da9-cccd-4d31-84ae-807368862b81">

**Comment by a2-4am** [comment]
<img width="950" alt="Screenshot 2024-05-11 at 7 06 59 PM" src="https://github.com/a2-4am/4cade/assets/22437310/df753ffa-373a-4b13-baa0-bdfcdb7926a3">

**Comment by peterferrie** [comment]
That looks to be Virtual II's problem.  Bejeweled installs an interrupt
handler which sets the address at $BF37, which clearly hasn't happened here.
Perhaps Virtual II's reset does not bank ROM back in like it should.  I
will investigate it.

**Comment by peterferrie** [comment]
It's a TR bug, nothing to do with Bejeweled.  I will fix this.
