### ISSUE TITLE
Game keyboard instructions

### ISSUE THREAD

**Issue by roughana** [a2-4am/4cade#58]
Trying to use the keyboard is frustrating if the keys to use are not known. e.g. Berzap
Some indication of keys to use would be very helpful especially if they are not able to be configured.
Perhaps a splash screen with Keys can be displayed before the game is loaded?

**Comment by peterferrie** [comment]
You're suggesting that we read the manual for you? :-)

**Comment by a2-4am** [comment]
This came up at Kansasfest as well, and I've seen the problem firsthand while watching Cat stream Total Replay on Twitch and choose random games to try them out. Some sort of in-app one-page help screen would be helpful for a lot of games.

We have no plans to implement this in v3, but I will leave this issue open for tracking purposes.

**Comment by roughana** [comment]
The framework for this is now implemented in v4 and gamehelp screens are being contributed.
I think we can close this now.
