### ISSUE TITLE
Bongo's Bash crashes on start

### ISSUE THREAD

**Issue by frankmilliron** [a2-4am/4cade#591]
Crashes to Applesoft showing "?FORMULA TOO COMPLEX ERROR IN 5000".

**Comment by peterferrie** [comment]
fixed in dbfb04301880115a13a8262259e58eee5ca045c8

**Comment by frankmilliron** [comment]
now crashes showing:
3639-    A=08 X=01 Y=04 P=36 S=F2
*

**Comment by peterferrie** [comment]
Ha, I don't see the crash if I boot ProDOS first, only if I boot directly.
I've missed something.
