### ISSUE TITLE
Galactic Attack hangs on start

### ISSUE THREAD

**Issue by frankmilliron** [a2-4am/4cade#595]
Shows a message on screen "SYSTEM.PASCAL not found" on //e.

Seems to run properly on a (emulated) ][+.

**Comment by peterferrie** [comment]
I can't reproduce it in MAME or AppleWin.  Is it Virtual II?

**Comment by frankmilliron** [comment]
Yes

**Comment by peterferrie** [comment]
I can't reproduce this in Virtual II.  Please send a save-state.

**Comment by frankmilliron** [comment]
Attached. Thanks for looking into it.
[Galactic.viisnapshot.zip](https://github.com/user-attachments/files/15830610/Galactic.viisnapshot.zip)

**Comment by peterferrie** [comment]
fixed in f618e901c641a87ac9abcf97e0938ad207611bce.  It needed to see a floppy drive in slot 6.
