### ISSUE TITLE
Marble Madness hangs on start

### ISSUE THREAD

**Issue by frankmilliron** [a2-4am/4cade#597]
When playing the intro screen music, game just hangs once you press a key to start.

**Comment by peterferrie** [comment]
I can't reproduce this in Virtual II.  Please send a save-state.

**Comment by frankmilliron** [comment]
Sure thing. Attached.
[Marble.viisnapshot.zip](https://github.com/user-attachments/files/15830650/Marble.viisnapshot.zip)

**Comment by frankmilliron** [comment]
If I hit the joystick button during the music it starts normally. If I hit space bar it hangs. GAMES.CONF says it's joystick only.

**Comment by peterferrie** [comment]
Keys trigger the some debugging code, but it shouldn't hang.  I'll try it.

**Comment by peterferrie** [comment]
When I press space, the music stops but it doesn't hang for me.  I can start a game by pressing OA.  OA is the only way to start the game.

**Comment by frankmilliron** [comment]
Weird! but okay!
