### ISSUE TITLE
Attract mode hangs on the Apple //c

### ISSUE THREAD

**Issue by cybernesto** [a2-4am/4cade#6]
The attract mode will leave the screen black after a random time. Tested on Apple //c models A2S4000 with ROM 4X and an SPVHD and an A2S4100 with a BMOW FloppyEmu with FW0.2I.
Not all possible screens were checked but LadyTut’s demo and Apple Cider Spider Demo have cause this already.

**Comment by peterferrie** [comment]
We might have overlooked some $C020s.  I'll check those images.

**Comment by a2-4am** [comment]
Is this fixed in 2.0-beta1, which includes https://github.com/a2-4am/4cade/commit/fa6a014c7764f74975d590bd4ede8c2362fdf8e1 ?

**Comment by cybernesto** [comment]
I can confirm that the attract mode works reliably on the mentioned configuration.
