### ISSUE TITLE
Planetoids hangs just after game start

### ISSUE THREAD

**Issue by frankmilliron** [a2-4am/4cade#600]
Just after the game field is drawn, a couple frames will advance then the game hangs.

**Comment by peterferrie** [comment]
I can't reproduce this in Virtual II.  Please send a save-state.

**Comment by frankmilliron** [comment]
OK weird. Virtual ][ is just beachballing when I try to save a Machine Snapshot.
Nevermind... If I remove the Z80 card it works.

**Comment by peterferrie** [comment]
That's still a thing to fix.  I will try with the Z80 card.

**Comment by frankmilliron** [comment]
The main game loop runs from $821 to $851. It runs through three times normally, then hangs on the fourth time through the loop, on the JSR $ED2, never exiting the loop from $F1E to $F37.

**Comment by peterferrie** [comment]
That loop has a guaranteed exit condition, so it's something else maybe corrupting the code.  Please send a save-state.

**Comment by frankmilliron** [comment]
Wow. I really can't save a Machine State without hanging Virtual ][.
The indirect, indexed read at $F2E (and others) from $70/71 may be getting corrupted. Points to $C2A0 once it's hung and I can see it looping through softswitch addresses it shouldn't. One of those has to be activating the Z80 hardware.

**Comment by peterferrie** [comment]
There's a theme here.  $600-7FF content is missing in Marble Madness (which then causes the hang on pressing space), and presumably is damaged here, too (it holds the pointers used to set $70-71).  I will keep looking.

**Comment by peterferrie** [comment]
Please send a save-state before starting play.  Maybe I can trace from that point.

**Comment by frankmilliron** [comment]
Attached. PC was at $95E when I halted it. Hit 'P' to start.
[Planetoids.viisnapshot.zip](https://github.com/user-attachments/files/15920924/Planetoids.viisnapshot.zip)

**Comment by peterferrie** [comment]
Perfect.  It's a game bug.  I will fix it.

**Comment by peterferrie** [comment]
fixed in d52883974c62b14914afdc96a04a6b1797d85864
