### ISSUE TITLE
Fail to load on Apple //e with 65C816

### ISSUE THREAD

**Issue by TMS2764** [a2-4am/4cade#61]
Total Replay v2.0 fails to load on an enhanced Apple //e equipped with a 65C816 processor (A2Heaven 65C816->65C02 board).

**Comment by peterferrie** [comment]
This might be fixed in TR3, where we use a different detection for OS, and avoid a 65C816 instruction until we know that we're on a GS.

**Comment by TMS2764** [comment]
Sounds like plan. Just trying to help. Will try again when available.

**Comment by peterferrie** [comment]
does this boot?
http://pferrie.host22.com/misc/tmp/4cade.zip

**Comment by TMS2764** [comment]
Yes! It now works with the 65C816 processor in my //e. It also works with my stock //c+ which it did not before without using a boot disk. Good job.

**Comment by peterferrie** [comment]
Great.  Thanks.
