### ISSUE TITLE
Red Alert default keyboard controls are wonky

### ISSUE THREAD

**Issue by a2-4am** [a2-4am/4cade#617]
According to printed documentation, default controls should be A/Z to move crosshairs vertically and left/right arrows to move crosshairs horizontally, Space to fire normally and S to fire the mega-rocket. Our current port seems to use A for everything vertically (up, down, and stop) and right arrow for everything horizontally (left, right, and stop). Unclear if data corruption, a latent protection check. or simply user error.

**Comment by peterferrie** [comment]
fixed in e2075254f78eaff846a086a4cf8e724aa57d6622
