### ISSUE TITLE
Panic Button quits to monitor on Ctrl-Q

### ISSUE THREAD

**Issue by a2-4am** [a2-4am/4cade#627]
<img width="1288" alt="Screenshot 2024-07-06 at 10 54 45 AM" src="https://github.com/a2-4am/4cade/assets/22437310/a22e3c35-5931-43ef-838d-5eb30818fc90">

**Comment by peterferrie** [comment]
fixed in 1715396a3649e330cab00b37d8e13cd3f86772b7
