### ISSUE TITLE
Bug in Cross City Level 9

### ISSUE THREAD

**Issue by wyatt-wong** [a2-4am/4cade#631]
I found the game description information of "Cross City" from Computing Age magazine issue 40 (in Traditional Chinese). It was mentioned that at the start of the game, press 0 to 9 to choose from level 0 to level 9. I found that after pressing digit 9 at the beginning of the game, the game will mess up and failed to load the background of level 9. Please refer to the images below:

<img width="1282" alt="Bug in Cross City Level 9" src="https://github.com/user-attachments/assets/f7055840-5b1d-4b8b-9537-c4ee49420a57">

<img width="1282" alt="Unload to load the background in Level 9" src="https://github.com/user-attachments/assets/bde32a61-1802-496e-aa2c-dc3c95564334">

For comparison, please find the the background of the game from level 0 to level 8

Level 0

![Level 0](https://github.com/user-attachments/assets/5231b614-fa64-40c5-8f3a-f04a98f591bf)

Level 1

![Level 1](https://github.com/user-attachments/assets/5a469d15-205e-4110-b24e-3ebbbdc8a58d)

Level 2

![Level 2](https://github.com/user-attachments/assets/4d0f699e-fd1d-461b-a621-4ec7634a8979)

Level 3

![Level 3](https://github.com/user-attachments/assets/6065ae07-fb6a-4d56-82fb-6da78d45d165)

Level 4

![Level 4](https://github.com/user-attachments/assets/84e6b6ac-46e8-4c26-bfa3-d21c7066cf5a)

Level 5

![Level 5](https://github.com/user-attachments/assets/84785262-c122-4414-a9be-33361c768d2e)

Level 6

![Level 6](https://github.com/user-attachments/assets/d78e56f3-70b7-4757-bcb1-72caea4fe861)

Level 7

![Level 7](https://github.com/user-attachments/assets/d0ba8bc7-d55c-4000-b56e-331af0d8737f)

Level 8

![Level 8](https://github.com/user-attachments/assets/857dd702-eac2-4569-b576-2766ab427f4c)

**Comment by wyatt-wong** [comment]
I downloaded the Cross City game from Abandonware below and also found the game had the same bug and failed to load the background of level 9

https://www.myabandonware.com/game/cross-city-nvi#download

**Comment by peterferrie** [comment]
It's not a bug.  The level 9 background is entirely black.

**Comment by wyatt-wong** [comment]
> It's not a bug. The level 9 background is entirely black.

I found that from another guy. Even though it is NOT a bug, there is still a scrambled screen while loading level 9.

**Comment by wyatt-wong** [comment]
@peterferrie Please find the article in Chinese for reference:

![image](https://github.com/user-attachments/assets/8888bd10-bdd7-40c2-aba5-ea9be6193d27)

![image](https://github.com/user-attachments/assets/1f714ef2-267c-49cc-a269-48b9787b74ae)

![image](https://github.com/user-attachments/assets/58d93fc6-fe3a-42ab-83fc-555156170431)

![image](https://github.com/user-attachments/assets/aa2af031-d232-40df-bcc7-77976a40c383)
