### ISSUE TITLE
Black Magic game in Total Replay 5.2 is bad

### ISSUE THREAD

**Issue by megaman85** [a2-4am/4cade#633]
In Total Replay 5.1 and 5.2 the game "Black Magic" has issues when the player dies and goes to the enter score screen.

After I enter the score and press a key, the graphics become corrupt and goes into an endless loop of asking to enter score.

Tested and confirmed issue on a real Apple //e Enhanced running Booti and on AppleWin emulating Apple //e.

Please see video.

https://github.com/user-attachments/assets/28575c9d-ce68-441c-b57f-707080b30793

**Comment by peterferrie** [comment]
Thank you, I can reproduce the problem.  I will fix it.

**Comment by peterferrie** [comment]
fixed in 01d57dea03a17cab313842ace94a6133bf4bc125
