### ISSUE TITLE
TR 5.2 Angry Birds Issues

### ISSUE THREAD

**Issue by roughana** [a2-4am/4cade#636]
Angry Birds requires joystick to play (button 0). Update Games.conf to restrict to joystick only.

Angry Birds crashes to monitor on Quit from internal menu.

**Comment by peterferrie** [comment]
Angry Birds requires only open-apple (guaranteed to exist due to 128kb requirement), rather than joystick.
It is advertised as being playable with a keyboard.  The menu requires a joystick to select the other options, but they're considered optional.
I see the crash, though.  I will fix this.

**Comment by roughana** [comment]
Comment from 4am in Slack
Look I don't care either way but technically Angry Birds as a program is not fully navigable without a joystick. You can press Open Apple to select 'play' because that's the default item, but the other items in the main menu require a joystick to navigate to.

Subsequently the bit was flipped to reflect that a joystick is required.
