### ISSUE TITLE
Fail to load on Apple //c+

### ISSUE THREAD

**Issue by frankmilliron** [a2-4am/4cade#65]
I just picked up a //c+ today and tested it out with a Floppy Emu. Neither v2 or v3alpha will boot directly via SmartPort. I can start v2 using the ProDOS 2.0.3 launcher, but v3 crashes after the initial text screen before starting hires graphics. It seems like others are able to use TR on the //c+. Are they using an extended partition and booting from something else rather than ProBoot? I haven't made a recent ProDOS version boot disk to test with, but that's something I can try out to narrow down where it's hanging.

Looking forward to the new code that accelerates the unpacking. Part of why I thought it would be cool to pick this machine up.

f

**Comment by frankmilliron** [comment]
The same setup appears to be able to boot ProDOS 2.5a7 directly from the Floppy Emu.

**Comment by frankmilliron** [comment]
When it's the second partition on the Floppy Emu, v2 shows up as S5,D3 in Bitsy and crashes with "RUN FROM PARTITION 1-4". Version 3 alpha hangs at the intro text screen before switching to hires.

**Comment by peterferrie** [comment]
v2 can't run from D3.
Current v3 builds should work.  If it doesn't then please report the
build number that you used (it's displayed for all builds since about
three weeks ago).

**Comment by frankmilliron** [comment]
Not seeing a build number. It's "Total Replay v3.0-alpha.1.2mg" from....
https://archive.org/download/TotalReplay/Total%20Replay%20v3.0-alpha.1.2mg

**Comment by peterferrie** [comment]
The one with build numbers isn't released publicly yet but some people
have been building from source and sharing those, and it's hard to
track bugs when we don't know the exact version that was used.  Now we
do.

**Comment by peterferrie** [comment]
fixed in 9ff8b7e0a764b04c11b2c8d3f1b4a369cca8bb29.
FloppyEmu allows booting from drive 2.
