### ISSUE TITLE
Chip Out hangs at game over

### ISSUE THREAD

**Issue by badvision** [a2-4am/4cade#650]
After losing your last life in Chip Out, it is not possible to restart the game.  However, I noticed that moving the paddle all the way to the right it makes a tone as if you've touched the ball again.  Somehow it's stuck in a game loop instead of resetting.

**Comment by peterferrie** [comment]
This is original behaviour.  If you wiggle the joystick near the top left and right, eventually the game restarts.

**Comment by badvision** [comment]
Oh interesting!  Thanks for following up on that!  What a strange decision by the original programmer.
