### ISSUE TITLE
Adding Kaboom! for Apple II?

### ISSUE THREAD

**Issue by seanahan5000** [a2-4am/4cade#652]
My remake of Kaboom! for Apple II is available to be added to Instant Replay if you think it makes sense.

https://github.com/seanahan5000/kaboom

**Comment by peterferrie** [comment]
Thank you, it looks like a good candidate for Total Replay rather than Instant Replay, being more action than a sport. :-)
I will add it tomorrow.

**Comment by peterferrie** [comment]
done in 2cc6a9c9aa74dee44e22af81dd107e3f215450e2
