### ISSUE TITLE
Frogger II joystick routines suck

### ISSUE THREAD

**Issue by badvision** [a2-4am/4cade#658]
Apparently the joystick routines at $9AD4 try to read both axes at the same time but not very well. It is especially difficult to move right

Optional: The game also has no keyboard support even though realistically it would probably work fine with 4-way movement and action keys.

**Comment by peterferrie** [comment]
fixed in 89e13c6140e9b2bc2bc25c360389378e5f76f3f5

**Comment by badvision** [comment]
You flipping rule. Thanks!!!

**Comment by frankmilliron** [comment]
9AD4 is getting overwritten after hitting the button to start, by the original joystick routine.

**Comment by peterferrie** [comment]
oops.  ac2428bd9e5a4527a2edee4e20b9fe6f7ce7f621
