### ISSUE TITLE
Request: Create 'clean' 1 game per file prodos images for all games

### ISSUE THREAD

**Issue by rcampbel3** [a2-4am/4cade#659]
It sure would be wonderful to have a curated collection of single-game per image Apple 2 games without extra programs or multiple disks. Would it be possible for this project to generate a set of prodos images - one per game - that boot straight to that game for the greater good of the emulation community?

**Comment by roughana** [comment]
All the games that are included in Total Replay have already been ported to ProDOS. That was the inspiration behind creating a compendium in the first place.
You can find all the files that Total Replay uses here
https://github.com/a2-4am/4cade/tree/main/res/dsk
Total Replay focuses on Action Games, so there are other ProDOS ports that are not included in Total Replay.
You may find these on Asimov or Internet Archive.

**Comment by xotmatrix** [comment]
In particular, I'd look at the san_inc_prodos collection on Asimov, which is a huge collection of individual game disks converted to ProDOS by qkumba.

**Comment by wyatt-wong** [comment]
> It sure would be wonderful to have a curated collection of single-game per image Apple 2 games without extra programs or multiple disks. Would it be possible for this project to generate a set of prodos images - one per game - that boot straight to that game for the greater good of the emulation community?

The Sports related games are located in https://github.com/a2-4am/4sports/. The latest build of Total Replay and Instant Replay binaries can be found under two Facebook clubs managed by myself.

**Comment by wyatt-wong** [comment]
> It sure would be wonderful to have a curated collection of single-game per image Apple 2 games without extra programs or multiple disks. Would it be possible for this project to generate a set of prodos images - one per game - that boot straight to that game for the greater good of the emulation community?

Would you elaborate more about what you mean by single game per image and what EXACTLY is your expected result or outcome ?

**Comment by peterferrie** [comment]
This is resolved.  All games are in bootable single-image format already.
