### ISSUE TITLE
Ctrl+Reset during Mockingboard speech titles can result in repeated phoneme playback

### ISSUE THREAD

**Issue by tomcw** [a2-4am/4cade#660]
This affects SSI263 speech titles and probably SC01 titles too.

Background:
- /RESET is not connected to the speech chips, so when CTRL+RESET is pressed, then the speech chips are not reset.
- The speech chips have a feature in that they will repeatedly play back the same phoneme unless it's changed/volume set to 0/chip set to power-down mode (or phoneme set to PAUSE, which is just a silent phoneme).

Reproducible:
- During the speech phrase for eg. Berzap or Willy Byte then press CTRL+RESET midway through a speech phrase.
   - Berzap: when you die it speaks a long phrase
   - Willy Byte: when you boot the game, at the intro screen it speaks a long phrase
- TR will return to its main menu.
- Mostly (but not always) it'll result in the repeated phoneme play back.

NB. This doesn't reproduce with Rescue Raiders, as CTRL+RESET forces a reboot, and goes via the Mockingboard & speech chip detection code, which will silence any playing phonemes.

You can reproduce this using AppleWin 1.30.19 (or higher), but just for SSI263-based games. (The SC01 phonene repeat "feature" hasn't been enabled yet in AppleWin.)

(I have reproduced on real hardware just using .dsk images for Berzap or Willy Byte... as I didn't have a hard disk controller in my machine to test TR itself.)

**Comment by peterferrie** [comment]
fixed in b6deaebea94f6ace4a65a97fef542cafee6d7fb1
