### ISSUE TITLE
Swap button for Lode Runner Championship

### ISSUE THREAD

**Issue by PaulLouviers** [a2-4am/4cade#663]
Is it possible to swap Joystick button '0' & '1' in Lode Runner Championship, as it has been done for Lode Runner ? thank you

**Comment by peterferrie** [comment]
It's a good idea.  Fixed in a8dfafa221b60e44f6d95055f4c55b3acd512452

**Comment by wyatt-wong** [comment]
I found 2 recent updates on the 4cade GitHub source but I was surprised there was no change in the build number after I compiled them.
I guessed the build number need to be changed accordingly where there is change in the source code.
Best Regards,
Wyatt WongMessage ID: ***@***.***>
