### ISSUE TITLE
Mockingboard Noise on reset/power cycle?

### ISSUE THREAD

**Issue by frankmilliron** [a2-4am/4cade#70]
Sometimes reset leaves the mockingboard in a bad state, so noise is persistent from the output on reboot. Takes a minute or two of being off to reset the registers. Would be nice if TR could detect a mockingboard and set all registers to silent mode and baseline settings when doing the first initialization. This could be coupled with detecting which slot a mockingboard is on, and using it to set the active slot.

**Comment by a2-4am** [comment]
Mockingboard detection and auto-configuration is planned for v4.

**Comment by frankmilliron** [comment]
Seems to be mostly fixed with TomCh's new mock code. Might be a hardware problem on my end otherwise.

**Comment by roughana** [comment]
FYI there was a design flaw with the original Mockingboard: the reset line was not connected to the AY which could leave a sound playing indefinitely. This was fixed with the Mockingboard C and derivatives.
