### ISSUE TITLE
Glitches in Mr. Do level 8

### ISSUE THREAD

**Issue by a2-4am** [a2-4am/4cade#8]
![image](https://user-images.githubusercontent.com/22437310/62483619-2376ce00-b786-11e9-8051-2d29c5689dc9.png)

**Comment by wyatt-wong** [comment]
The problem happen again whenever I reached Level 8 in Mr. Do in TotalReplay..
<img width="1060" alt="Screen Shot 2019-08-06 at 1 31 11 AM" src="https://user-images.githubusercontent.com/10095648/62483845-49828980-b7eb-11e9-8357-60d205eb8a12.png">

**Comment by peterferrie** [comment]
fixed in 15e2d00e710e93c933be5efa3eadc6a1163a8fb5
