### ISSUE TITLE
Freeze on David's Midnight Magic on IIgs with Micro-Drive Turbo

### ISSUE THREAD

**Issue by erangell** [a2-4am/4cade#97]
I put the 32mb image of Version 3.0 beta 2 on a Floppy Emu and copied all files to an internal Micro-Drive Turbo in slot 7.  The files are in a subdirectory on S7, D2.  I can run Total Replay and play games.  David's Midnight Magic freezes when I start to play the game - see attached.  I have not had time to test other configs but can help test modifications.
![DMM](https://user-images.githubusercontent.com/5579123/71724647-001c8180-2dff-11ea-8d32-0ae7999c49f5.jpg)

**Comment by peterferrie** [comment]
Is the DAVIDS.MAGIC.2 file present in the same directory as
DAVIDS.MAGIC and DAVIDS.MAGIC.1?

**Comment by erangell** [comment]
Yes it is.  When I run DAVIDS.MAGIC from Bitsy Bye the game runs correctly.
I also tested putting the CF card in an Apple //e with a MicroDrive Turbo.  The game was not available when searching or browsing through the available games, as if it was a GS only game.  I did not have any issues when running the image on a Floppy Emu on any computer.

**Comment by peterferrie** [comment]
> Yes it is.  When I run DAVIDS.MAGIC from Bitsy Bye the game runs correctly.

Okay, that sounds like my bug.

> I also tested putting the CF card in an Apple //e with a MicroDrive Turbo.
> The game was not available when searching or browsing through the available
> games, as if it was a GS only game.

That's a design issue - it's listed as requiring a joystick, along
with Nigh Mission, but both can run on a IIe or better because of
open/closed Apple keys.  Raster Blaster should be marked similarly and
for the same reason, but isn't currently.

**Comment by a2-4am** [comment]
What program did you use to copy the files?

**Comment by peterferrie** [comment]
> Yes it is. The path is: /MDVOL2/TOTAL.REPLAY/X/DAVIDS.MAGIC

Ohhh, I missed this previously.  We don't support that.  TR games run from "/X" only.

**Comment by erangell** [comment]
I used Copy 2+ ver 9.1
Later this week I will test moving the directories to the root of the volume and see if it changes the behavior.  Thanks!

**Comment by erangell** [comment]
Copying the files under TOTAL.REPLAY to the root of a new partition solved the problem!
You may want to add an FAQ about this.
So the only open issue is updating configurations for pinball games that can run without a joystick on 2e or greater.
Thanks for all your help.
