### ISSUE TITLE
Speedway Classic Crashes Apple IIGS When Gameplay Starts

### ISSUE THREAD

**Issue by HelixNRG** [a2-4am/4cade#98]
On a ROM3 Apple IIGS using a CFFA3000 with Total Replay v3 beta 2, the game instantly crashes as soon as gameplay is about to start when you've selected joystick control. If keyboard control is specified, the game plays normally.

**Comment by peterferrie** [comment]
Does it show the race track first?

**Comment by frankmilliron** [comment]
Can confirm. Does show the race track. Plays the starting lights music and crashes immediately to the //gs "check startup drive" without showing "Apple //gs" after playing the last note. I can't seem to reproduce it in MAME however.

**Comment by frankmilliron** [comment]
there's some LDA C020,x (X=10)accesses for the joystick routine to hit the speaker (9A93,9AA1,9B50). keyboard and starting light music uses BIT C030. Not sure if that's relevant.

**Comment by frankmilliron** [comment]
$925:JSR FB25 is the where it hangs. LC/ROM/gsROM switched in incorrectly??

looks like it's should be going to FB25:LDA $C064,X (][ ROM paddle) and is hitting some '816 opcodes on the //gs instead.

//gs monitor listing on break shows...
FB25: ADC (20)
AND (0D),Y
TCD
ADC 6F
ROR 5D
ORA 468D
XCE
etc etc

tricky tricky... had to change the SEI to CLI in prelaunch to get monitor to work.

**Comment by peterferrie** [comment]
I don't think that the GS offers the right routine at $FB25.  The game might simply not be able to run there.

**Comment by peterferrie** [comment]
Frank will make a prelaunch patch for it.

**Comment by frankmilliron** [comment]
that was a weird one to track down. they changed the beginning subroutine code to jump somewhere else and replaced the rest of the code on //gs with '816 instructions.
